paths:
  /accounts/{ACCOUNT_ID}/configs/{CONFIG_ID}:
    delete:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/CONFIG_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Delete an instance of configs
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/CONFIG_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets a configs by ID
    patch:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/CONFIG_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../oas3-schemas.yml#/configs'
      responses:
        200:
          description: Successful operation
      summary: Patch specific fields of configs
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/CONFIG_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../oas3-schemas.yml#/configs'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of configs
    put:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/CONFIG_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../oas3-schemas.yml#/configs'
      responses:
        200:
          description: Successful operation
      summary: Add an instance of configs
