'delete':
  'operationId': delete.configs.0cd22c
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/CONFIG_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Delete an instance of configs
'get':
  'operationId': get.configs.9a20a1
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/CONFIG_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Gets a configs by ID
'patch':
  'operationId': patch.configs.65769a
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/CONFIG_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'requestBody':
    'application/json':
      'schema':
        '$ref': '../oas3-schemas.yml#/configs'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Patch specific fields of configs
'post':
  'operationId': post.configs.022f90
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/CONFIG_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'requestBody':
    'application/json':
      'schema':
        '$ref': '../oas3-schemas.yml#/configs'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Update an instance of configs
'put':
  'operationId': put.configs.0d3a6b
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/CONFIG_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'requestBody':
    'application/json':
      'schema':
        '$ref': '../oas3-schemas.yml#/configs'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Add an instance of configs
