'delete':
  'operationId': delete.services.bdc6b0
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/PLAN_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Delete an instance of services
'get':
  'operationId': get.services.41ea33
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/AUDIT_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Gets a services by ID
'patch':
  'operationId': patch.services.2c3ae5
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'requestBody':
    'application/json':
      'schema':
        '$ref': '../oas3-schemas.yml#/services'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Patch specific fields of services
'post':
  'operationId': post.services.65f2e0
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'requestBody':
    'application/json':
      'schema':
        '$ref': '../oas3-schemas.yml#/services'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Update an instance of services
