'delete':
  'operationId': delete.services.3360d0
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/PLAN_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Delete an instance of services
'get':
  'operationId': get.services.959c36
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/AUDIT_ID'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Gets a services by ID
'patch':
  'operationId': patch.services.8284cc
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'requestBody':
    'application/json':
      'schema':
        '$ref': '../oas3-schemas.yml#/services'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Patch specific fields of services
'post':
  'operationId': post.services.533464
  'parameters':
    - '$ref': '../oas3-parameters.yml#/auth_token_header'
    - '$ref': '../oas3-parameters.yml#/ACCOUNT_ID'
  'requestBody':
    'application/json':
      'schema':
        '$ref': '../oas3-schemas.yml#/services'
  'responses':
    '200':
      'summary': Successful operation
  'summary': Update an instance of services
