paths:
  /accounts/{ACCOUNT_ID}/services:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets all services
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of services
  /accounts/{ACCOUNT_ID}/services/audit:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets audit of services
  /accounts/{ACCOUNT_ID}/services/audit/{AUDIT_ID}:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/AUDIT_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets a services by ID
  /accounts/{ACCOUNT_ID}/services/available:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets available of services
  /accounts/{ACCOUNT_ID}/services/editable:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets editable of services
  /accounts/{ACCOUNT_ID}/services/manual:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets manual of services
    patch:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Patch specific fields of services
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of services
  /accounts/{ACCOUNT_ID}/services/overrides:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets overrides of services
    patch:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Patch specific fields of services
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of services
  /accounts/{ACCOUNT_ID}/services/quote:
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of services
  /accounts/{ACCOUNT_ID}/services/reconciliation:
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of services
  /accounts/{ACCOUNT_ID}/services/summary:
    get:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Gets summary of services
  /accounts/{ACCOUNT_ID}/services/synchronization:
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of services
  /accounts/{ACCOUNT_ID}/services/topup:
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of services
  /accounts/{ACCOUNT_ID}/services/{PLAN_ID}:
    delete:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/PLAN_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Delete an instance of services
    post:
      parameters:
        - $ref: '../oas3-parameters.yml#/auth_token_header'
        - $ref: '../oas3-parameters.yml#/PLAN_ID'
        - $ref: '../oas3-parameters.yml#/ACCOUNT_ID'
      responses:
        200:
          description: Successful operation
      summary: Update an instance of services
