language: erlang
otp_release:
# Test on all supported releases accepted by the `require_otp_vsn` in rebar.config
  - 17.0
  - R16B03-1
#  - R16B03 this version is broken!
  - R16B02
  - R16B01
  - R16B
#  - R15B03-1 not available on travis
  - R15B03
  - R15B02

# since Travis is naughty and calls rebar get-deps behind our backs,
# we'll have to clean it up and build merl our selves..
script: "make -C deps/merl && make tests"

notifications:
  irc: "chat.freenode.net#erlydtl"
