#!/bin/sh
# Copyright 2010, Scatterbit, Inc. & Jayson Vantuyl <jvantuyl@scatterbit.com>
#
# This file is part of erlctl.
#
# Erlctl is open source.  See LICENSE.txt for details.

# Adapting rabbitmqctl pieces into here

#!/bin/sh

cd `dirname $0`
export ERL_LIBS=$PWD/../lib/

EBIN=ebin
DIAG_EBIN=$PWD/../utils/diagnostics/ebin
ERL_COOKIE=`grep "setcookie" conf/vm.args`
NODENAME=ecallmgrctl@`hostname -f`

exec erl \
    -pa $EBIN $DIAG_EBIN \
    -name $NODENAME \
    $ERL_COOKIE \
    +Bd \
    -noshell \
    -mode interactive \
    -s erlctl_cmd \
    -extra "$0" "$@"
