#!/bin/bash

cd `dirname $0`/../utils/sup/
echo
echo "===================================[ This command has been depreciated!!! ]==================================="
echo 
echo "  We appologize for any inconvience, but hope that you find the 'sup' command a more flexable and usefull tool."
echo "  Its output and return value is much more conducive to scripting.  We also plan to use it at the lowlevel"
echo "  for a series of much more user friendly scripts (comming shortly).  Furthermore, the 'sup' command can"
echo "  connect to remote serves, meaning you can manage all your nodes from one system. More details are available"
echo "  on the 2600hz wiki!  --Thank you"
echo
echo "Please make note of the following command replacements:"
echo " * ecallmgr_ctl add_fs_node freeswitch@2600hz.com"
echo "     > $PWD/sup -n ecallmgr ecallmgr_maintenance add_fs_node freeswitch@2600hz.com"
echo
echo " * ecallmgr_ctl rm_fs_node freeswitch@2600hz.com"
echo "     > $PWD/sup -n ecallmgr ecallmgr_maintenance remove_fs_node freeswitch@2600hz.comp"
echo
echo " * ecallmgr_ctl status"
echo "     > $PWD/sup -n ecallmgr ecallmgr_maintenance list_fs_nodes"
echo 
echo "New commands:"
echo " * List technical details about the calls currently being processed by this ecallmgr"
echo "     > $PWD/sup -n ecallmgr ecallmgr_maintenance show_calls"
echo
echo " * List the freeswitch nodes that this ecallmgr is configured to connect to"
echo "     > $PWD/sup -n ecallmgr ecallmgr_config get fs_nodes"
echo
echo "To save yourself from having to type the full path each time you can run(per user):"
echo "    > $PWD/add_alias.sh"
echo
echo "=============================================================================================================="
echo
