%% Copyright (C) 07/01/2010 Dmitry S. Melnikov (dmitryme@gmail.com)
%%
%% This program is free software; you can redistribute it and/or
%% modify it under the terms of the GNU General Public License
%% as published by the Free Software Foundation; either version 2
%% of the License, or (at your option) any later version.
%%
%% This program is distributed in the hope that it will be useful,
%% but WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%% GNU General Public License for more details.
%%
%% You should have received a copy of the GNU General Public License
%% along with this program; if not, write to the Free Software
%% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-author("Dmitry Melnikov <dmitryme@gmail.com>").

% {TimeZoneName, {StdAbbr, StdName}, {DstAbbr, DstName}, StdMin, DstMin, DstStartDay, DstStartTime, DstEndDay, DstEndTime}
%   TimeZoneName = String(), TimeZone name, MUST be unique. It is a key
%   StdName = {String(), String()}, name and abbreviations of timezone before daylight shift
%   DstName = {String(), String()}, name and abbreviations of timezone after daylight shift
%   StdMin = Integer(), GMT offset in minutes. W/o daylight savings
%   DstMin = Integer(), daylight saving. Adjustment for GMT offset, when daylight saving is on
%   DstStartDay = {NthWeekday, Weekday, Month}, daylight saving transition rule. Can be undef if no daylight saving rule specified
%     NthWeekday = Integer(), 1(first week),2(second week),3(...),4(...),5(...),-1(last week)
%     Weekday = atom(),  sun,mon,tue,wed,thu,fri,sat
%     Month = atom(),  jan,deb,mar,apr,may,jun,jul,aug,sep,oct,mov,dec
%   DstStartTime = {Hour, Min} - time of daylight saving transition
%     Hour = Integer(), [0..23]
%     Min = Integer(), [0..59]
%   DstEndDay = {NthWeekday, Weekday, Month} - transition back to std. Can be undef if no daylight saving rule specified
%   {Hour, Min} - time of transition to std.
% }

-type dow() :: 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat'.
-type moy() :: 'jan' | 'feb' | 'mar' | 'apr' | 'may' | 'jun' | 'jul' | 'aug' | 'sep' | 'oct' | 'nov' | 'dec'.

-type stdname() :: {string(), string()}.
-type dstname() :: 'undef' | {string(), string()}.
-type shift() :: integer().
-type dstshift() :: shift().
-type dstrule() :: 'undef' | {integer(), dow(), moy()}.
-type dsttime() :: {integer(), integer()}.


%% TzName, StdName, DstName, Shift, DstShift, DstStartRule, DstStartTime, DstEndRule, DstEndTime
-type tz_db_row() :: {string(), stdname(), dstname(), shift(), dstshift(), dstrule(), dsttime(), dstrule(), dsttime()}.

-define(tz_database,
   [
      {"Africa/Abidjan",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Accra",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Addis Ababa",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Africa/Algiers",{"CET","CET"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Asmera",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Africa/Bamako",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Bangui",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Banjul",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Bissau",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Blantyre",{"CAT","CAT"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Brazzaville",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Bujumbura",{"CAT","CAT"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Cairo",{"EET","EET"},{"EEST","EEST"},120,60,{last,fri,apr},{0,0},{last,fri,sep},{0,0}},
      {"Africa/Casablanca",{"WET","WET"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Ceuta",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Africa/Conakry",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Dakar",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Dar es Salaam",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Africa/Djibouti",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Africa/Douala",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/El Aaiun",{"WET","WET"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Freetown",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Gaborone",{"CAT","CAT"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Harare",{"CAT","CAT"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Johannesburg",{"SAST","SAST"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Kampala",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Africa/Khartoum",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Africa/Kigali",{"CAT","CAT"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Kinshasa",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Lagos",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Libreville",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Lome",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Luanda",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Lubumbashi",{"CAT","CAT"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Lusaka",{"CAT","CAT"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Malabo",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Maputo",{"CAT","CAT"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Maseru",{"SAST","SAST"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Mbabane",{"SAST","SAST"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Mogadishu",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Africa/Monrovia",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Nairobi",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Africa/Ndjamena",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Niamey",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Nouakchott",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Ouagadougou",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Porto-Novo",{"WAT","WAT"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Sao Tome",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Timbuktu",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Africa/Tripoli",{"EET","EET"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Africa/Tunis",{"CET","CET"},undef,60,0,undef,{0,0},undef,{0,0}},
      {"Africa/Windhoek",{"WAT","WAT"},{"WAST","WAST"},60,60,{1,sun,sep},{2,0},{1,sun,apr},{2,0}},
      {"America/Adak",{"HAST","HAST"},{"HADT","HADT"},-600,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Anchorage",{"AKST","AKST"},{"AKDT","AKDT"},-540,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Anguilla",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Antigua",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Araguaina",{"BRT","BRT"},{"BRST","BRST"},-180,60,{2,sun,oct},{0,0},{3,sun,feb},{0,0}},
      {"America/Aruba",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Asuncion",{"PYT","PYT"},{"PYST","PYST"},-240,60,{1,sun,oct},{0,0},{1,sun,mar},{0,0}},
      {"America/Barbados",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Belem",{"BRT","BRT"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Belize",{"CST","CST"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"America/Boa Vista",{"AMT","AMT"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Bogota",{"COT","COT"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/Boise",{"MST","MST"},{"MDT","MDT"},-420,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Buenos Aires",{"ART","ART"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Cambridge Bay",{"MST","MST"},{"MDT","MDT"},-420,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Cancun",{"CST","CST"},{"CDT","CDT"},-360,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"America/Caracas",{"VET","VET"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Catamarca",{"ART","ART"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Cayenne",{"GFT","GFT"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Cayman",{"EST","EST"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/Chicago",{"CST","Central Standard Time"},{"CDT","Central Daylight Time"},-360,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Chihuahua",{"MST","MST"},{"MDT","MDT"},-420,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"America/Cordoba",{"ART","ART"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Costa Rica",{"CST","CST"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"America/Cuiaba",{"AMT","AMT"},{"AMST","AMST"},-240,60,{2,sun,oct},{0,0},{3,sun,feb},{0,0}},
      {"America/Curacao",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Danmarkshavn",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"America/Dawson",{"PST","PST"},{"PDT","PDT"},-480,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Dawson Creek",{"MST","MST"},undef,-420,0,undef,{0,0},undef,{0,0}},
      {"America/Denver",{"MST","Mountain Standard Time"},{"MDT","Mountain Daylight Time"},-420,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Detroit",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Dominica",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Edmonton",{"MST","MST"},{"MDT","MDT"},-420,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Eirunepe",{"ACT","ACT"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/El Salvador",{"CST","CST"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"America/Fortaleza",{"BRT","BRT"},{"BRST","BRST"},-180,60,{2,sun,oct},{0,0},{3,sun,feb},{0,0}},
      {"America/Glace Bay",{"AST","AST"},{"ADT","ADT"},-240,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Godthab",{"WGT","WGT"},{"WGST","WGST"},-180,60,{last,sat,mar},{22,0},{last,sat,oct},{23,0}},
      {"America/Goose Bay",{"AST","AST"},{"ADT","ADT"},-240,60,{1,sun,apr},{0,1},{last,sun,oct},{0,1}},
      {"America/Grand Turk",{"EST","EST"},{"EDT","EDT"},-300,60,{1,sun,apr},{0,0},{last,sun,oct},{0,0}},
      {"America/Grenada",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Guadeloupe",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Guatemala",{"CST","CST"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"America/Guayaquil",{"ECT","ECT"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/Guyana",{"GYT","GYT"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Halifax",{"AST","AST"},{"ADT","ADT"},-240,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Havana",{"CST","CST"},{"CDT","CDT"},-300,60,{1,sun,apr},{0,0},{last,sun,oct},{1,0}},
      {"America/Hermosillo",{"MST","MST"},undef,-420,0,undef,{0,0},undef,{0,0}},
      {"America/Indiana/Indianapolis",{"EST","EST"},undef,-300,0,{2,sun,mar},{0,0},{1,sun,nov},{0,0}},
      {"America/Indiana/Knox",{"EST","EST"},undef,-300,0,{2,sun,mar},{0,0},{1,sun,nov},{0,0}},
      {"America/Indiana/Marengo",{"EST","EST"},undef,-300,0,{2,sun,mar},{0,0},{1,sun,nov},{0,0}},
      {"America/Indiana/Vevay",{"EST","EST"},undef,-300,0,{2,sun,mar},{0,0},{1,sun,nov},{0,0}},
      {"America/Indianapolis",{"EST","EST"},undef,-300,0,{2,sun,mar},{0,0},{1,sun,nov},{0,0}},
      {"America/Inuvik",{"MST","MST"},{"MDT","MDT"},-420,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Iqaluit",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Jamaica",{"EST","EST"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/Jujuy",{"ART","ART"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Juneau",{"AKST","AKST"},{"AKDT","AKDT"},-540,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Kentucky/Louisville",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Kentucky/Monticello",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/La Paz",{"BOT","BOT"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Lima",{"PET","PET"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/Los Angeles",{"PST","Pacific Standard Time"},{"PDT","Pacific Daylight Time"},-480,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Louisville",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Maceio",{"BRT","BRT"},{"BRST","BRST"},-180,60,{2,sun,oct},{0,0},{3,sun,feb},{0,0}},
      {"America/Managua",{"CST","CST"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"America/Manaus",{"AMT","AMT"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Martinique",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Mazatlan",{"MST","MST"},{"MDT","MDT"},-420,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"America/Mendoza",{"ART","ART"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Menominee",{"CST","CST"},{"CDT","CDT"},-360,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Merida",{"CST","CST"},{"CDT","CDT"},-360,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"America/Mexico City",{"CST","CST"},{"CDT","CDT"},-360,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"America/Miquelon",{"PMST","PMST"},{"PMDT","PMDT"},-180,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Monterrey",{"CST","CST"},{"CDT","CDT"},-360,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"America/Montevideo",{"UYT","UYT"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Montreal",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Montserrat",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Nassau",{"EST","EST"},{"EDT","EDT"},-300,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"America/New York",{"EST","Eastern Standard Time"},{"EDT","Eastern Daylight Time"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Nipigon",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Nome",{"AKST","AKST"},{"AKDT","AKDT"},-540,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Noronha",{"FNT","FNT"},undef,-120,0,undef,{0,0},undef,{0,0}},
      {"America/North Dakota/Center",{"CST","CST"},{"CDT","CDT"},-360,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Panama",{"EST","EST"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/Pangnirtung",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Paramaribo",{"SRT","SRT"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Phoenix",{"MST","Mountain Standard Time"},undef,-420,0,undef,{0,0},undef,{0,0}},
      {"America/Port-au-Prince",{"EST","EST"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/Port of Spain",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Porto Velho",{"AMT","AMT"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Puerto Rico",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Rainy River",{"CST","CST"},{"CDT","CDT"},-360,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Rankin Inlet",{"CST","CST"},{"CDT","CDT"},-360,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Recife",{"BRT","BRT"},{"BRST","BRST"},-180,60,{2,sun,oct},{0,0},{3,sun,feb},{0,0}},
      {"America/Regina",{"CST","CST"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"America/Rio Branco",{"ACT","ACT"},undef,-300,0,undef,{0,0},undef,{0,0}},
      {"America/Rosario",{"ART","ART"},undef,-180,0,undef,{0,0},undef,{0,0}},
      {"America/Santiago",{"CLT","CLT"},{"CLST","CLST"},-240,60,{2,sun,oct},{0,0},{2,sun,mar},{0,0}},
      {"America/Santo Domingo",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Sao Paulo",{"BRT","BRT"},{"BRST","BRST"},-180,60,{2,sun,oct},{0,0},{3,sun,feb},{0,0}},
      {"America/Scoresbysund",{"EGT","EGT"},{"EGST","EGST"},-60,60,{last,sun,mar},{0,0},{last,sun,oct},{1,0}},
      {"America/Shiprock",{"MST","MST"},{"MDT","MDT"},-420,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/St Johns",{"NST","NST"},{"NDT","NDT"},-210,60,{1,sun,apr},{0,1},{last,sun,oct},{0,1}},
      {"America/St Kitts",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/St Lucia",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/St Thomas",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/St Vincent",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Swift Current",{"CST","CST"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"America/Tegucigalpa",{"CST","CST"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"America/Thule",{"AST","AST"},undef,-240,0,{2,sun,mar},{0,0},{1,sun,nov},{0,0}},
      {"America/Thunder Bay",{"EST","EST"},{"EDT","EDT"},-300,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Tijuana",{"PST","PST"},{"PDT","PDT"},-480,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"America/Tortola",{"AST","AST"},undef,-240,0,undef,{0,0},undef,{0,0}},
      {"America/Vancouver",{"PST","PST"},{"PDT","PDT"},-480,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Whitehorse",{"PST","PST"},{"PDT","PDT"},-480,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Winnipeg",{"CST","CST"},{"CDT","CDT"},-360,60,{2,sun,mar},{2,0},{1,sun,nov},{3,0}},
      {"America/Yakutat",{"AKST","AKST"},{"AKDT","AKDT"},-540,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"America/Yellowknife",{"MST","MST"},{"MDT","MDT"},-420,60,{2,sun,mar},{2,0},{1,sun,nov},{2,0}},
      {"Antarctica/Casey",{"WST","WST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Antarctica/Davis",{"DAVT","DAVT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Antarctica/DumontDUrville",{"DDUT","DDUT"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Antarctica/Mawson",{"MAWT","MAWT"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Antarctica/McMurdo",{"NZST","NZST"},{"NZDT","NZDT"},720,60,{1,sun,oct},{2,0},{3,sun,mar},{3,0}},
      {"Antarctica/Palmer",{"CLT","CLT"},{"CLST","CLST"},-240,60,{2,sun,oct},{0,0},{2,sun,mar},{0,0}},
      {"Antarctica/South Pole",{"NZST","NZST"},{"NZDT","NZDT"},720,60,{1,sun,oct},{2,0},{3,sun,mar},{3,0}},
      {"Antarctica/Syowa",{"SYOT","SYOT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Antarctica/Vostok",{"VOST","VOST"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Arctic/Longyearbyen",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Asia/Aden",{"AST","AST"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Asia/Almaty",{"ALMT","ALMT"},{"ALMST","ALMST"},360,60,{last,sun,mar},{0,0},{last,sun,oct},{0,0}},
      {"Asia/Amman",{"EET","EET"},{"EEST","EEST"},120,60,{last,thu,mar},{0,0},{last,thu,sep},{1,0}},
      {"Asia/Anadyr",{"ANAT","ANAT"},{"ANAST","ANAST"},720,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Asia/Aqtau",{"AQTT","AQTT"},{"AQTST","AQTST"},240,60,{last,sun,mar},{0,0},{last,sun,oct},{0,0}},
      {"Asia/Aqtobe",{"AQTT","AQTT"},{"AQTST","AQTST"},300,60,{last,sun,mar},{0,0},{last,sun,oct},{0,0}},
      {"Asia/Ashgabat",{"TMT","TMT"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Asia/Baghdad",{"AST","AST"},{"ADT","ADT"},180,60,{1,sun,apr},{3,0},{1,sun,oct},{4,0}},
      {"Asia/Bahrain",{"AST","AST"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Asia/Baku",{"AZT","AZT"},{"AZST","AZST"},240,60,{last,sun,mar},{1,0},{last,sun,oct},{1,0}},
      {"Asia/Bangkok",{"ICT","ICT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Asia/Beirut",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{0,0},{last,sun,oct},{0,0}},
      {"Asia/Bishkek",{"KGT","KGT"},{"KGST","KGST"},300,60,{last,sun,mar},{2,30},{last,sun,oct},{2,30}},
      {"Asia/Brunei",{"BNT","BNT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Calcutta",{"IST","IST"},undef,330,0,undef,{0,0},undef,{0,0}},
      {"Asia/Choibalsan",{"CHOT","CHOT"},undef,540,0,undef,{0,0},undef,{0,0}},
      {"Asia/Chongqing",{"CST","CST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Colombo",{"LKT","LKT"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Asia/Damascus",{"EET","EET"},{"EEST","EEST"},120,60,{1,sun,apr},{0,0},{1,sun,oct},{0,0}},
      {"Asia/Dhaka",{"BDT","BDT"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Asia/Dili",{"TPT","TPT"},undef,540,0,undef,{0,0},undef,{0,0}},
      {"Asia/Dubai",{"GST","GST"},undef,240,0,undef,{0,0},undef,{0,0}},
      {"Asia/Dushanbe",{"TJT","TJT"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Asia/Gaza",{"EET","EET"},{"EEST","EEST"},120,60,{3,fri,apr},{0,0},{3,fri,oct},{0,0}},
      {"Asia/Harbin",{"CST","CST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Hong Kong",{"HKT","HKT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Hovd",{"HOVT","HOVT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Asia/Irkutsk",{"IRKT","IRKT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Istanbul",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Asia/Jakarta",{"WIT","WIT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Asia/Jayapura",{"EIT","EIT"},undef,540,0,undef,{0,0},undef,{0,0}},
      {"Asia/Jerusalem",{"IST","IST"},{"IDT","IDT"},120,60,{1,sun,apr},{1,0},{1,sun,oct},{1,0}},
      {"Asia/Kabul",{"AFT","AFT"},undef,270,0,undef,{0,0},undef,{0,0}},
      {"Asia/Kamchatka",{"PETT","PETT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Asia/Karachi",{"PKT","PKT"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Asia/Kashgar",{"CST","CST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Katmandu",{"NPT","NPT"},undef,345,0,undef,{0,0},undef,{0,0}},
      {"Asia/Krasnoyarsk",{"KRAT","KRAT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Asia/Kuala Lumpur",{"MYT","MYT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Kuching",{"MYT","MYT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Kuwait",{"AST","AST"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Asia/Macao",{"CST","CST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Macau",{"CST","CST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Magadan",{"MAGT","MAGT"},undef,660,0,undef,{0,0},undef,{0,0}},
      {"Asia/Makassar",{"CIT","CIT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Manila",{"PHT","PHT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Muscat",{"GST","GST"},undef,240,0,undef,{0,0},undef,{0,0}},
      {"Asia/Nicosia",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Asia/Novosibirsk",{"NOVT","NOVT"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Asia/Omsk",{"OMST","OMST"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Asia/Oral",{"WST","WST"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Asia/Phnom Penh",{"ICT","ICT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Asia/Pontianak",{"WIT","WIT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Asia/Pyongyang",{"KST","KST"},undef,540,0,undef,{0,0},undef,{0,0}},
      {"Asia/Qyzylorda",{"KST","KST"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Asia/Qatar",{"AST","AST"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Asia/Rangoon",{"MMT","MMT"},undef,390,0,undef,{0,0},undef,{0,0}},
      {"Asia/Riyadh",{"AST","AST"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Asia/Saigon",{"ICT","ICT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Asia/Sakhalin",{"SAKT","SAKT"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Asia/Samarkand",{"UZT","UZT"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Asia/Seoul",{"KST","KST"},undef,540,0,undef,{0,0},undef,{0,0}},
      {"Asia/Shanghai",{"CST","CST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Singapore",{"SGT","SGT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Taipei",{"CST","CST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Tashkent",{"UZT","UZT"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Asia/Tbilisi",{"GET","GET"},{"GEST","GEST"},240,60,{last,sun,mar},{0,0},{last,sun,oct},{0,0}},
      {"Asia/Tehran",{"IRT","IRT"},undef,210,0,undef,{0,0},undef,{0,0}},
      {"Asia/Thimphu",{"BTT","BTT"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Asia/Tokyo",{"JST","JST"},undef,540,0,undef,{0,0},undef,{0,0}},
      {"Asia/Ujung Pandang",{"CIT","CIT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Ulaanbaatar",{"ULAT","ULAT"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Urumqi",{"CST","CST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Asia/Vientiane",{"ICT","ICT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Asia/Vladivostok",{"VLAT","VLAT"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Asia/Yakutsk",{"YAKT","YAKT"},undef,540,0,undef,{0,0},undef,{0,0}},
      {"Asia/Yekaterinburg",{"YEKT","YEKT"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Asia/Yerevan",{"AMT","AMT"},{"AMST","AMST"},240,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Atlantic/Azores",{"AZOT","AZOT"},{"AZOST","AZOST"},-60,60,{last,sun,mar},{0,0},{last,sun,oct},{1,0}},
      {"Atlantic/Bermuda",{"AST","AST"},{"ADT","ADT"},-240,60,{1,sun,apr},{2,0},{last,sun,oct},{2,0}},
      {"Atlantic/Canary",{"WET","WET"},{"WEST","WEST"},0,60,{last,sun,mar},{1,0},{last,sun,oct},{2,0}},
      {"Atlantic/Cape Verde",{"CVT","CVT"},undef,-60,0,undef,{0,0},undef,{0,0}},
      {"Atlantic/Faeroe",{"WET","WET"},{"WEST","WEST"},0,60,{last,sun,mar},{1,0},{last,sun,oct},{2,0}},
      {"Atlantic/Jan Mayen",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Atlantic/Madeira",{"WET","WET"},{"WEST","WEST"},0,60,{last,sun,mar},{1,0},{last,sun,oct},{2,0}},
      {"Atlantic/Reykjavik",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Atlantic/South Georgia",{"GST","GST"},undef,-120,0,undef,{0,0},undef,{0,0}},
      {"Atlantic/St Helena",{"GMT","GMT"},undef,0,0,undef,{0,0},undef,{0,0}},
      {"Atlantic/Stanley",{"FKT","FKT"},{"FKST","FKST"},-240,60,{1,sun,sep},{2,0},{3,sun,apr},{2,0}},
      {"Australia/Adelaide",{"CST","CST"},{"CST","CST"},570,60,{last,sun,oct},{2,0},{last,sun,mar},{3,0}},
      {"Australia/Brisbane",{"EST","EST"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Australia/Broken Hill",{"CST","CST"},{"CST","CST"},570,60,{last,sun,oct},{2,0},{last,sun,mar},{3,0}},
      {"Australia/Darwin",{"CST","CST"},undef,570,0,undef,{0,0},undef,{0,0}},
      {"Australia/Hobart",{"EST","EST"},{"EST","EST"},600,60,{1,sun,oct},{2,0},{last,sun,mar},{3,0}},
      {"Australia/Lindeman",{"EST","EST"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Australia/Lord Howe",{"LHST","LHST"},{"LHST","LHST"},630,30,{last,sun,oct},{2,0},{last,sun,mar},{2,0}},
      {"Australia/Melbourne",{"EST","EST"},{"EST","EST"},600,60,{last,sun,oct},{2,0},{last,sun,mar},{3,0}},
      {"Australia/Perth",{"WST","WST"},undef,480,0,undef,{0,0},undef,{0,0}},
      {"Australia/Sydney",{"EST","EST"},{"EST","EST"},600,60,{last,sun,oct},{2,0},{last,sun,mar},{3,0}},
      {"Europe/Amsterdam",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Andorra",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Athens",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Belfast",{"GMT","GMT"},{"BST","BST"},0,60,{last,sun,mar},{1,0},{last,sun,oct},{2,0}},
      {"Europe/Belgrade",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Berlin",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Bratislava",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Brussels",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Bucharest",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Budapest",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Chisinau",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Copenhagen",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Dublin",{"GMT","GMT"},{"IST","IST"},0,60,{last,sun,mar},{1,0},{last,sun,oct},{2,0}},
      {"Europe/Gibraltar",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Helsinki",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Istanbul",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Kaliningrad",{"EET","EET"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Europe/Kiev",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Lisbon",{"WET","WET"},{"WEST","WEST"},0,60,{last,sun,mar},{1,0},{last,sun,oct},{2,0}},
      {"Europe/Ljubljana",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/London",{"GMT","GMT"},{"BST","BST"},0,60,{last,sun,mar},{1,0},{last,sun,oct},{2,0}},
      {"Europe/Luxembourg",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Madrid",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Malta",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Minsk",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Monaco",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Moscow",{"MSK","MSK"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Europe/Nicosia",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Oslo",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Paris",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Prague",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Riga",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Rome",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Samara",{"SAMT","SAMT"},undef,240,0,undef,{0,0},undef,{0,0}},
      {"Europe/San Marino",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Sarajevo",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Simferopol",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Skopje",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Sofia",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Stockholm",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Tallinn",{"EET","EET"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Europe/Tirane",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Uzhgorod",{"EET","EET"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Europe/Vaduz",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Vatican",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Vienna",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Vilnius",{"EET","EET"},undef,120,0,undef,{0,0},undef,{0,0}},
      {"Europe/Warsaw",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Zagreb",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Europe/Zaporozhye",{"EET","EET"},{"EEST","EEST"},120,60,{last,sun,mar},{3,0},{last,sun,oct},{4,0}},
      {"Europe/Zurich",{"CET","CET"},{"CEST","CEST"},60,60,{last,sun,mar},{2,0},{last,sun,oct},{3,0}},
      {"Indian/Antananarivo",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Indian/Chagos",{"IOT","IOT"},undef,360,0,undef,{0,0},undef,{0,0}},
      {"Indian/Christmas",{"CXT","CXT"},undef,420,0,undef,{0,0},undef,{0,0}},
      {"Indian/Cocos",{"CCT","CCT"},undef,390,0,undef,{0,0},undef,{0,0}},
      {"Indian/Comoro",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Indian/Kerguelen",{"TFT","TFT"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Indian/Mahe",{"SCT","SCT"},undef,240,0,undef,{0,0},undef,{0,0}},
      {"Indian/Maldives",{"MVT","MVT"},undef,300,0,undef,{0,0},undef,{0,0}},
      {"Indian/Mauritius",{"MUT","MUT"},undef,240,0,undef,{0,0},undef,{0,0}},
      {"Indian/Mayotte",{"EAT","EAT"},undef,180,0,undef,{0,0},undef,{0,0}},
      {"Indian/Reunion",{"RET","RET"},undef,240,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Apia",{"WST","WST"},undef,-660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Auckland",{"NZST","NZST"},{"NZDT","NZDT"},720,60,{1,sun,oct},{2,0},{3,sun,mar},{3,0}},
      {"Pacific/Chatham",{"CHAST","CHAST"},{"CHADT","CHADT"},765,60,{1,sun,oct},{2,45},{3,sun,mar},{3,45}},
      {"Pacific/Easter",{"EAST","EAST"},{"EASST","EASST"},-360,60,{2,sat,oct},{22,0},{2,sat,mar},{22,0}},
      {"Pacific/Efate",{"VUT","VUT"},undef,660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Enderbury",{"PHOT","PHOT"},undef,780,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Fakaofo",{"TKT","TKT"},undef,-600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Fiji",{"FJT","FJT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Funafuti",{"TVT","TVT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Galapagos",{"GALT","GALT"},undef,-360,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Gambier",{"GAMT","GAMT"},undef,-540,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Guadalcanal",{"SBT","SBT"},undef,660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Guam",{"ChST","ChST"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Honolulu",{"HST","HST"},undef,-600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Johnston",{"HST","HST"},undef,-600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Kiritimati",{"LINT","LINT"},undef,840,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Kosrae",{"KOST","KOST"},undef,660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Kwajalein",{"MHT","MHT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Majuro",{"MHT","MHT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Marquesas",{"MART","MART"},undef,-570,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Midway",{"SST","SST"},undef,-660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Nauru",{"NRT","NRT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Niue",{"NUT","NUT"},undef,-660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Norfolk",{"NFT","NFT"},undef,690,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Noumea",{"NCT","NCT"},undef,660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Pago Pago",{"SST","SST"},undef,-660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Palau",{"PWT","PWT"},undef,540,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Pitcairn",{"PST","PST"},undef,-480,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Ponape",{"PONT","PONT"},undef,660,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Port Moresby",{"PGT","PGT"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Rarotonga",{"CKT","CKT"},undef,-600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Saipan",{"ChST","ChST"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Tahiti",{"TAHT","TAHT"},undef,-600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Tarawa",{"GILT","GILT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Tongatapu",{"TOT","TOT"},undef,780,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Truk",{"TRUT","TRUT"},undef,600,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Wake",{"WAKT","WAKT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Wallis",{"WFT","WFT"},undef,720,0,undef,{0,0},undef,{0,0}},
      {"Pacific/Yap",{"YAPT","YAPT"},undef,600,0,undef,{0,0},undef,{0,0}}
   ]).
