-define(tz_index, [{"WGST",["America/Godthab"]},
		   {"SST",["Pacific/Midway","Pacific/Pago Pago"]},
		   {"ChST",["Pacific/Guam","Pacific/Saipan"]},
		   {"CCT",["Indian/Cocos"]},
		   {"NPT",["Asia/Katmandu"]},
		   {"AZST",["Asia/Baku"]},
		   {"AQTT",["Asia/Aqtau","Asia/Aqtobe"]},
		   {"NUT",["Pacific/Niue"]},
		   {"IRT",["Asia/Tehran"]},
		   {"HKT",["Asia/Hong Kong"]},
		   {"AZT",["Asia/Baku"]},
		   {"DAVT",["Antarctica/Davis"]},
		   {"WAST",["Africa/Windhoek"]},
		   {"PHT",["Asia/Manila"]},
		   {"MST",
		    ["America/Boise","America/Cambridge Bay","America/Chihuahua",
		     "America/Dawson Creek","America/Denver","America/Edmonton",
		     "America/Hermosillo","America/Inuvik","America/Mazatlan","America/Phoenix",
		     "America/Shiprock","America/Yellowknife"]},
		   {"SBT",["Pacific/Guadalcanal"]},
		   {"GAMT",["Pacific/Gambier"]},
		   {"MAGT",["Asia/Magadan"]},
		   {"KGST",["Asia/Bishkek"]},
		   {"DDUT",["Antarctica/DumontDUrville"]},
		   {"ADT",
		    ["America/Glace Bay","America/Goose Bay","America/Halifax","Asia/Baghdad",
		     "Atlantic/Bermuda"]},
		   {"SGT",["Asia/Singapore"]},
		   {"GST",["Asia/Dubai","Asia/Muscat","Atlantic/South Georgia"]},
		   {"NDT",["America/St Johns"]},
		   {"EET",
		    ["Africa/Cairo","Africa/Tripoli","Asia/Amman","Asia/Beirut","Asia/Damascus",
		     "Asia/Gaza","Asia/Istanbul","Asia/Nicosia","Europe/Athens",
		     "Europe/Bucharest","Europe/Chisinau","Europe/Helsinki","Europe/Istanbul",
		     "Europe/Kaliningrad","Europe/Kiev","Europe/Minsk","Europe/Nicosia",
		     "Europe/Riga","Europe/Simferopol","Europe/Sofia","Europe/Tallinn",
		     "Europe/Uzhgorod","Europe/Vilnius","Europe/Zaporozhye"]},
		   {"PWT",["Pacific/Palau"]},
		   {"PHOT",["Pacific/Enderbury"]},
		   {"RET",["Indian/Reunion"]},
		   {"MSK",["Europe/Moscow"]},
		   {"LHST",["Australia/Lord Howe","Australia/Lord Howe"]},
		   {"GEST",["Asia/Tbilisi"]},
		   {"UZT",["Asia/Samarkand","Asia/Tashkent"]},
		   {"SAKT",["Asia/Sakhalin"]},
		   {"EASST",["Pacific/Easter"]},
		   {"FKST",["Atlantic/Stanley"]},
		   {"AST",
		    ["America/Anguilla","America/Antigua","America/Aruba","America/Barbados",
		     "America/Curacao","America/Dominica","America/Glace Bay",
		     "America/Goose Bay","America/Grenada","America/Guadeloupe",
		     "America/Halifax","America/Martinique","America/Montserrat",
		     "America/Port of Spain","America/Puerto Rico","America/Santo Domingo",
		     "America/St Kitts","America/St Lucia","America/St Thomas",
		     "America/St Vincent","America/Thule","America/Tortola","Asia/Aden",
		     "Asia/Baghdad","Asia/Bahrain","Asia/Kuwait","Asia/Qatar","Asia/Riyadh",
		     "Atlantic/Bermuda"]},
		   {"CAT",
		    ["Africa/Blantyre","Africa/Bujumbura","Africa/Gaborone","Africa/Harare",
		     "Africa/Kigali","Africa/Lubumbashi","Africa/Lusaka","Africa/Maputo"]},
		   {"YEKT",["Asia/Yekaterinburg"]},
		   {"AQTST",["Asia/Aqtau","Asia/Aqtobe"]},
		   {"NST",["America/St Johns"]},
		   {"CKT",["Pacific/Rarotonga"]},
		   {"BDT",["Asia/Dhaka"]},
		   {"LINT",["Pacific/Kiritimati"]},
		   {"HST",["Pacific/Honolulu","Pacific/Johnston"]},
		   {"VUT",["Pacific/Efate"]},
		   {"MVT",["Indian/Maldives"]},
		   {"NOVT",["Asia/Novosibirsk"]},
		   {"PKT",["Asia/Karachi"]},
		   {"FJT",["Pacific/Fiji"]},
		   {"CHADT",["Pacific/Chatham"]},
		   {"BNT",["Asia/Brunei"]},
		   {"VOST",["Antarctica/Vostok"]},
		   {"ECT",["America/Guayaquil"]},
		   {"WAT",
		    ["Africa/Bangui","Africa/Brazzaville","Africa/Douala","Africa/Kinshasa",
		     "Africa/Lagos","Africa/Libreville","Africa/Luanda","Africa/Malabo",
		     "Africa/Ndjamena","Africa/Niamey","Africa/Porto-Novo","Africa/Windhoek"]},
		   {"WFT",["Pacific/Wallis"]},
		   {"KOST",["Pacific/Kosrae"]},
		   {"BST",["Europe/Belfast","Europe/London"]},
		   {"IDT",["Asia/Jerusalem"]},
		   {"HADT",["America/Adak"]},
		   {"EEST",
		    ["Africa/Cairo","Asia/Amman","Asia/Beirut","Asia/Damascus","Asia/Gaza",
		     "Asia/Istanbul","Asia/Nicosia","Europe/Athens","Europe/Bucharest",
		     "Europe/Chisinau","Europe/Helsinki","Europe/Istanbul","Europe/Kiev",
		     "Europe/Minsk","Europe/Nicosia","Europe/Riga","Europe/Simferopol",
		     "Europe/Sofia","Europe/Zaporozhye"]},
		   {"TVT",["Pacific/Funafuti"]},
		   {"AZOT",["Atlantic/Azores"]},
		   {"CHOT",["Asia/Choibalsan"]},
		   {"ALMT",["Asia/Almaty"]},
		   {"CHAST",["Pacific/Chatham"]},
		   {"CDT",
		    ["America/Cancun","America/Chicago","America/Havana","America/Menominee",
		     "America/Merida","America/Mexico City","America/Monterrey",
		     "America/North Dakota/Center","America/Rainy River","America/Rankin Inlet",
		     "America/Winnipeg"]},
		   {"SAST",["Africa/Johannesburg","Africa/Maseru","Africa/Mbabane"]},
		   {"GET",["Asia/Tbilisi"]},
		   {"CIT",["Asia/Makassar","Asia/Ujung Pandang"]},
		   {"IST",["Asia/Calcutta","Asia/Jerusalem","Europe/Dublin"]},
		   {"PDT",
		    ["America/Dawson","America/Los Angeles","America/Tijuana",
		     "America/Vancouver","America/Whitehorse"]},
		   {"PYST",["America/Asuncion"]},
		   {"HAST",["America/Adak"]},
		   {"PMDT",["America/Miquelon"]},
		   {"SCT",["Indian/Mahe"]},
		   {"MYT",["Asia/Kuala Lumpur","Asia/Kuching"]},
		   {"KRAT",["Asia/Krasnoyarsk"]},
		   {"TJT",["Asia/Dushanbe"]},
		   {"CST",
		    ["America/Belize","America/Cancun","America/Chicago","America/Costa Rica",
		     "America/El Salvador","America/Guatemala","America/Havana",
		     "America/Managua","America/Menominee","America/Merida",
		     "America/Mexico City","America/Monterrey","America/North Dakota/Center",
		     "America/Rainy River","America/Rankin Inlet","America/Regina",
		     "America/Swift Current","America/Tegucigalpa","America/Winnipeg",
		     "Asia/Chongqing","Asia/Harbin","Asia/Kashgar","Asia/Macao","Asia/Macau",
		     "Asia/Shanghai","Asia/Taipei","Asia/Urumqi","Australia/Adelaide",
		     "Australia/Adelaide","Australia/Broken Hill","Australia/Broken Hill",
		     "Australia/Darwin"]},
		   {"EAT",
		    ["Africa/Addis Ababa","Africa/Asmera","Africa/Dar es Salaam",
		     "Africa/Djibouti","Africa/Kampala","Africa/Khartoum","Africa/Mogadishu",
		     "Africa/Nairobi","Indian/Antananarivo","Indian/Comoro","Indian/Mayotte"]},
		   {"TOT",["Pacific/Tongatapu"]},
		   {"CXT",["Indian/Christmas"]},
		   {"VLAT",["Asia/Vladivostok"]},
		   {"ANAST",["Asia/Anadyr"]},
		   {"SYOT",["Antarctica/Syowa"]},
		   {"PST",
		    ["America/Dawson","America/Los Angeles","America/Tijuana",
		     "America/Vancouver","America/Whitehorse","Pacific/Pitcairn"]},
		   {"CEST",
		    ["Africa/Ceuta","Arctic/Longyearbyen","Atlantic/Jan Mayen",
		     "Europe/Amsterdam","Europe/Andorra","Europe/Belgrade","Europe/Berlin",
		     "Europe/Bratislava","Europe/Brussels","Europe/Budapest",
		     "Europe/Copenhagen","Europe/Gibraltar","Europe/Ljubljana",
		     "Europe/Luxembourg","Europe/Madrid","Europe/Malta","Europe/Monaco",
		     "Europe/Oslo","Europe/Paris","Europe/Prague","Europe/Rome",
		     "Europe/San Marino","Europe/Sarajevo","Europe/Skopje","Europe/Stockholm",
		     "Europe/Tirane","Europe/Vaduz","Europe/Vatican","Europe/Vienna",
		     "Europe/Warsaw","Europe/Zagreb","Europe/Zurich"]},
		   {"MART",["Pacific/Marquesas"]},
		   {"WIT",["Asia/Jakarta","Asia/Pontianak"]},
		   {"PMST",["America/Miquelon"]},
		   {"GYT",["America/Guyana"]},
		   {"AKDT",
		    ["America/Anchorage","America/Juneau","America/Nome","America/Yakutat"]},
		   {"MHT",["Pacific/Kwajalein","Pacific/Majuro"]},
		   {"AZOST",["Atlantic/Azores"]},
		   {"YAKT",["Asia/Yakutsk"]},
		   {"JST",["Asia/Tokyo"]},
		   {"ALMST",["Asia/Almaty"]},
		   {"MAWT",["Antarctica/Mawson"]},
		   {"SRT",["America/Paramaribo"]},
		   {"YAPT",["Pacific/Yap"]},
		   {"ULAT",["Asia/Ulaanbaatar"]},
		   {"MMT",["Asia/Rangoon"]},
		   {"WST",["Antarctica/Casey","Asia/Oral","Australia/Perth","Pacific/Apia"]},
		   {"CLST",["America/Santiago","Antarctica/Palmer"]},
		   {"PGT",["Pacific/Port Moresby"]},
		   {"WEST",
		    ["Atlantic/Canary","Atlantic/Faeroe","Atlantic/Madeira","Europe/Lisbon"]},
		   {"OMST",["Asia/Omsk"]},
		   {"LKT",["Asia/Colombo"]},
		   {"EGST",["America/Scoresbysund"]},
		   {"CLT",["America/Santiago","Antarctica/Palmer"]},
		   {"BRST",
		    ["America/Araguaina","America/Fortaleza","America/Maceio","America/Recife",
		     "America/Sao Paulo"]},
		   {"AKST",
		    ["America/Anchorage","America/Juneau","America/Nome","America/Yakutat"]},
		   {"GALT",["Pacific/Galapagos"]},
		   {"NZDT",["Antarctica/McMurdo","Antarctica/South Pole","Pacific/Auckland"]},
		   {"ACT",["America/Eirunepe","America/Rio Branco"]},
		   {"GMT",
		    ["Africa/Abidjan","Africa/Accra","Africa/Bamako","Africa/Banjul",
		     "Africa/Bissau","Africa/Conakry","Africa/Dakar","Africa/Freetown",
		     "Africa/Lome","Africa/Monrovia","Africa/Nouakchott","Africa/Ouagadougou",
		     "Africa/Sao Tome","Africa/Timbuktu","America/Danmarkshavn",
		     "Atlantic/Reykjavik","Atlantic/St Helena","Europe/Belfast","Europe/Dublin",
		     "Europe/London"]},
		   {"NCT",["Pacific/Noumea"]},
		   {"EAST",["Pacific/Easter"]},
		   {"FKT",["Atlantic/Stanley"]},
		   {"CVT",["Atlantic/Cape Verde"]},
		   {"PETT",["Asia/Kamchatka"]},
		   {"TMT",["Asia/Ashgabat"]},
		   {"BOT",["America/La Paz"]},
		   {"EDT",
		    ["America/Detroit","America/Grand Turk","America/Iqaluit",
		     "America/Kentucky/Louisville","America/Kentucky/Monticello",
		     "America/Louisville","America/Montreal","America/Nassau",
		     "America/New York","America/Nipigon","America/Pangnirtung",
		     "America/Thunder Bay"]},
		   {"BTT",["Asia/Thimphu"]},
		   {"KST",["Asia/Pyongyang","Asia/Qyzylorda","Asia/Seoul"]},
		   {"EIT",["Asia/Jayapura"]},
		   {"IRKT",["Asia/Irkutsk"]},
		   {"UYT",["America/Montevideo"]},
		   {"WGT",["America/Godthab"]},
		   {"AMT",
		    ["America/Boa Vista","America/Cuiaba","America/Manaus",
		     "America/Porto Velho","Asia/Yerevan"]},
		   {"WAKT",["Pacific/Wake"]},
		   {"TRUT",["Pacific/Truk"]},
		   {"NZST",["Antarctica/McMurdo","Antarctica/South Pole","Pacific/Auckland"]},
		   {"VET",["America/Caracas"]},
		   {"ART",
		    ["America/Buenos Aires","America/Catamarca","America/Cordoba",
		     "America/Jujuy","America/Mendoza","America/Rosario"]},
		   {"NRT",["Pacific/Nauru"]},
		   {"IOT",["Indian/Chagos"]},
		   {"ANAT",["Asia/Anadyr"]},
		   {"EST",
		    ["America/Cayman","America/Detroit","America/Grand Turk",
		     "America/Indiana/Indianapolis","America/Indiana/Knox",
		     "America/Indiana/Marengo","America/Indiana/Vevay","America/Indianapolis",
		     "America/Iqaluit","America/Jamaica","America/Kentucky/Louisville",
		     "America/Kentucky/Monticello","America/Louisville","America/Montreal",
		     "America/Nassau","America/New York","America/Nipigon","America/Panama",
		     "America/Pangnirtung","America/Port-au-Prince","America/Thunder Bay",
		     "Australia/Brisbane","Australia/Hobart","Australia/Hobart",
		     "Australia/Lindeman","Australia/Melbourne","Australia/Melbourne",
		     "Australia/Sydney","Australia/Sydney"]},
		   {"CET",
		    ["Africa/Algiers","Africa/Ceuta","Africa/Tunis","Arctic/Longyearbyen",
		     "Atlantic/Jan Mayen","Europe/Amsterdam","Europe/Andorra","Europe/Belgrade",
		     "Europe/Berlin","Europe/Bratislava","Europe/Brussels","Europe/Budapest",
		     "Europe/Copenhagen","Europe/Gibraltar","Europe/Ljubljana",
		     "Europe/Luxembourg","Europe/Madrid","Europe/Malta","Europe/Monaco",
		     "Europe/Oslo","Europe/Paris","Europe/Prague","Europe/Rome",
		     "Europe/San Marino","Europe/Sarajevo","Europe/Skopje","Europe/Stockholm",
		     "Europe/Tirane","Europe/Vaduz","Europe/Vatican","Europe/Vienna",
		     "Europe/Warsaw","Europe/Zagreb","Europe/Zurich"]},
		   {"TAHT",["Pacific/Tahiti"]},
		   {"PONT",["Pacific/Ponape"]},
		   {"HOVT",["Asia/Hovd"]},
		   {"PET",["America/Lima"]},
		   {"GFT",["America/Cayenne"]},
		   {"MUT",["Indian/Mauritius"]},
		   {"TFT",["Indian/Kerguelen"]},
		   {"KGT",["Asia/Bishkek"]},
		   {"COT",["America/Bogota"]},
		   {"TKT",["Pacific/Fakaofo"]},
		   {"AFT",["Asia/Kabul"]},
		   {"GILT",["Pacific/Tarawa"]},
		   {"NFT",["Pacific/Norfolk"]},
		   {"TPT",["Asia/Dili"]},
		   {"ICT",["Asia/Bangkok","Asia/Phnom Penh","Asia/Saigon","Asia/Vientiane"]},
		   {"EGT",["America/Scoresbysund"]},
		   {"FNT",["America/Noronha"]},
		   {"BRT",
		    ["America/Araguaina","America/Belem","America/Fortaleza","America/Maceio",
		     "America/Recife","America/Sao Paulo"]},
		   {"WET",
		    ["Africa/Casablanca","Africa/El Aaiun","Atlantic/Canary","Atlantic/Faeroe",
		     "Atlantic/Madeira","Europe/Lisbon"]},
		   {"SAMT",["Europe/Samara"]},
		   {"AMST",["America/Cuiaba","Asia/Yerevan"]},
		   {"MDT",
		    ["America/Boise","America/Cambridge Bay","America/Chihuahua",
		     "America/Denver","America/Edmonton","America/Inuvik","America/Mazatlan",
		     "America/Shiprock","America/Yellowknife"]},
		   {"PYT",["America/Asuncion"]}]
       ).
