-define(tz_index, {dict,164,33,64,32,165,99,
                        {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                        {{[["WGST","America/Godthab"]],
                          [["AQTT","Asia/Aqtau","Asia/Aqtobe"],
                           ["AZST","Asia/Baku"],
                           ["NPT","Asia/Katmandu"],
                           ["CCT","Indian/Cocos"],
                           ["ChST","Pacific/Guam","Pacific/Saipan"],
                           ["SST","Pacific/Midway","Pacific/Pago Pago"]],
                          [["WAST","Africa/Windhoek"],
                           ["DAVT","Antarctica/Davis"],
                           ["AZT","Asia/Baku"],
                           ["HKT","Asia/Hong Kong"],
                           ["IRT","Asia/Tehran"],
                           ["NUT","Pacific/Niue"]],
                          [["MST","America/Boise","America/Cambridge Bay",
                            "America/Chihuahua","America/Dawson Creek",
                            "America/Denver","America/Edmonton",
                            "America/Hermosillo","America/Inuvik",
                            "America/Mazatlan","America/Phoenix",
                            "America/Shiprock","America/Yellowknife"],
                           ["PHT","Asia/Manila"]],
                          [["ADT","America/Glace Bay","America/Goose Bay",
                            "America/Halifax","Asia/Baghdad",
                            "Atlantic/Bermuda"],
                           ["DDUT","Antarctica/DumontDUrville"],
                           ["KGST","Asia/Bishkek"],
                           ["MAGT","Asia/Magadan"],
                           ["GAMT","Pacific/Gambier"],
                           ["SBT","Pacific/Guadalcanal"]],
                          [["EET","Africa/Cairo","Africa/Tripoli",
                            "Asia/Amman","Asia/Beirut","Asia/Damascus",
                            "Asia/Gaza","Asia/Istanbul","Asia/Nicosia",
                            "Europe/Athens","Europe/Bucharest",
                            "Europe/Chisinau","Europe/Helsinki",
                            "Europe/Istanbul","Europe/Kaliningrad",
                            "Europe/Kiev","Europe/Minsk","Europe/Nicosia",
                            "Europe/Riga","Europe/Simferopol","Europe/Sofia",
                            "Europe/Tallinn","Europe/Uzhgorod",
                            "Europe/Vilnius","Europe/Zaporozhye"],
                           ["NDT","America/St Johns"],
                           ["GST","Asia/Dubai","Asia/Muscat",
                            "Atlantic/South Georgia"],
                           ["SGT","Asia/Singapore"]],
                          [["SAKT","Asia/Sakhalin"],
                           ["UZT","Asia/Samarkand","Asia/Tashkent"],
                           ["GEST","Asia/Tbilisi"],
                           ["LHST","Australia/Lord Howe",
                            "Australia/Lord Howe"],
                           ["MSK","Europe/Moscow"],
                           ["RET","Indian/Reunion"],
                           ["PHOT","Pacific/Enderbury"],
                           ["PWT","Pacific/Palau"]],
                          [["CAT","Africa/Blantyre","Africa/Bujumbura",
                            "Africa/Gaborone","Africa/Harare","Africa/Kigali",
                            "Africa/Lubumbashi","Africa/Lusaka",
                            "Africa/Maputo"],
                           ["AST","America/Anguilla","America/Antigua",
                            "America/Aruba","America/Barbados",
                            "America/Curacao","America/Dominica",
                            "America/Glace Bay","America/Goose Bay",
                            "America/Grenada","America/Guadeloupe",
                            "America/Halifax","America/Martinique",
                            "America/Montserrat","America/Port of Spain",
                            "America/Puerto Rico","America/Santo Domingo",
                            "America/St Kitts","America/St Lucia",
                            "America/St Thomas","America/St Vincent",
                            "America/Thule","America/Tortola","Asia/Aden",
                            "Asia/Baghdad","Asia/Bahrain","Asia/Kuwait",
                            "Asia/Qatar","Asia/Riyadh","Atlantic/Bermuda"],
                           ["FKST","Atlantic/Stanley"],
                           ["EASST","Pacific/Easter"]],
                          [["NST","America/St Johns"],
                           ["AQTST","Asia/Aqtau","Asia/Aqtobe"],
                           ["YEKT","Asia/Yekaterinburg"]],
                          [["BDT","Asia/Dhaka"],["CKT","Pacific/Rarotonga"]],
                          [["PKT","Asia/Karachi"],
                           ["NOVT","Asia/Novosibirsk"],
                           ["MVT","Indian/Maldives"],
                           ["VUT","Pacific/Efate"],
                           ["HST","Pacific/Honolulu","Pacific/Johnston"],
                           ["LINT","Pacific/Kiritimati"]],
                          [["WAT","Africa/Bangui","Africa/Brazzaville",
                            "Africa/Douala","Africa/Kinshasa","Africa/Lagos",
                            "Africa/Libreville","Africa/Luanda",
                            "Africa/Malabo","Africa/Ndjamena","Africa/Niamey",
                            "Africa/Porto-Novo","Africa/Windhoek"],
                           ["ECT","America/Guayaquil"],
                           ["VOST","Antarctica/Vostok"],
                           ["BNT","Asia/Brunei"],
                           ["CHADT","Pacific/Chatham"],
                           ["FJT","Pacific/Fiji"]],
                          [["EEST","Africa/Cairo","Asia/Amman","Asia/Beirut",
                            "Asia/Damascus","Asia/Gaza","Asia/Istanbul",
                            "Asia/Nicosia","Europe/Athens","Europe/Bucharest",
                            "Europe/Chisinau","Europe/Helsinki",
                            "Europe/Istanbul","Europe/Kiev","Europe/Minsk",
                            "Europe/Nicosia","Europe/Riga",
                            "Europe/Simferopol","Europe/Sofia",
                            "Europe/Zaporozhye"],
                           ["HADT","America/Adak"],
                           ["IDT","Asia/Jerusalem"],
                           ["BST","Europe/Belfast","Europe/London"],
                           ["KOST","Pacific/Kosrae"],
                           ["WFT","Pacific/Wallis"]],
                          [["ALMT","Asia/Almaty"],
                           ["CHOT","Asia/Choibalsan"],
                           ["AZOT","Atlantic/Azores"],
                           ["TVT","Pacific/Funafuti"]],
                          [["SAST","Africa/Johannesburg","Africa/Maseru",
                            "Africa/Mbabane"],
                           ["CDT","America/Cancun","America/Chicago",
                            "America/Havana","America/Menominee",
                            "America/Merida","America/Mexico City",
                            "America/Monterrey","America/North Dakota/Center",
                            "America/Rainy River","America/Rankin Inlet",
                            "America/Winnipeg"],
                           ["CHAST","Pacific/Chatham"]],
                          [["HAST","America/Adak"],
                           ["PYST","America/Asuncion"],
                           ["PDT","America/Dawson","America/Los Angeles",
                            "America/Tijuana","America/Vancouver",
                            "America/Whitehorse"],
                           ["IST","Asia/Calcutta","Asia/Jerusalem",
                            "Europe/Dublin"],
                           ["CIT","Asia/Makassar","Asia/Ujung Pandang"],
                           ["GET","Asia/Tbilisi"]]},
                         {[["PMDT","America/Miquelon"]],
                          [["EAT","Africa/Addis Ababa","Africa/Asmera",
                            "Africa/Dar es Salaam","Africa/Djibouti",
                            "Africa/Kampala","Africa/Khartoum",
                            "Africa/Mogadishu","Africa/Nairobi",
                            "Indian/Antananarivo","Indian/Comoro",
                            "Indian/Mayotte"],
                           ["CST","America/Belize","America/Cancun",
                            "America/Chicago","America/Costa Rica",
                            "America/El Salvador","America/Guatemala",
                            "America/Havana","America/Managua",
                            "America/Menominee","America/Merida",
                            "America/Mexico City","America/Monterrey",
                            "America/North Dakota/Center",
                            "America/Rainy River","America/Rankin Inlet",
                            "America/Regina","America/Swift Current",
                            "America/Tegucigalpa","America/Winnipeg",
                            "Asia/Chongqing","Asia/Harbin","Asia/Kashgar",
                            "Asia/Macao","Asia/Macau","Asia/Shanghai",
                            "Asia/Taipei","Asia/Urumqi","Australia/Adelaide",
                            "Australia/Adelaide","Australia/Broken Hill",
                            "Australia/Broken Hill","Australia/Darwin"],
                           ["TJT","Asia/Dushanbe"],
                           ["KRAT","Asia/Krasnoyarsk"],
                           ["MYT","Asia/Kuala Lumpur","Asia/Kuching"],
                           ["SCT","Indian/Mahe"]],
                          [["CEST","Africa/Ceuta","Arctic/Longyearbyen",
                            "Atlantic/Jan Mayen","Europe/Amsterdam",
                            "Europe/Andorra","Europe/Belgrade",
                            "Europe/Berlin","Europe/Bratislava",
                            "Europe/Brussels","Europe/Budapest",
                            "Europe/Copenhagen","Europe/Gibraltar",
                            "Europe/Ljubljana","Europe/Luxembourg",
                            "Europe/Madrid","Europe/Malta","Europe/Monaco",
                            "Europe/Oslo","Europe/Paris","Europe/Prague",
                            "Europe/Rome","Europe/San Marino",
                            "Europe/Sarajevo","Europe/Skopje",
                            "Europe/Stockholm","Europe/Tirane","Europe/Vaduz",
                            "Europe/Vatican","Europe/Vienna","Europe/Warsaw",
                            "Europe/Zagreb","Europe/Zurich"],
                           ["PST","America/Dawson","America/Los Angeles",
                            "America/Tijuana","America/Vancouver",
                            "America/Whitehorse","Pacific/Pitcairn"],
                           ["SYOT","Antarctica/Syowa"],
                           ["ANAST","Asia/Anadyr"],
                           ["VLAT","Asia/Vladivostok"],
                           ["CXT","Indian/Christmas"],
                           ["TOT","Pacific/Tongatapu"]],
                          [["AKDT","America/Anchorage","America/Juneau",
                            "America/Nome","America/Yakutat"],
                           ["GYT","America/Guyana"],
                           ["PMST","America/Miquelon"],
                           ["WIT","Asia/Jakarta","Asia/Pontianak"],
                           ["MART","Pacific/Marquesas"]],
                          [["SRT","America/Paramaribo"],
                           ["MAWT","Antarctica/Mawson"],
                           ["ALMST","Asia/Almaty"],
                           ["JST","Asia/Tokyo"],
                           ["YAKT","Asia/Yakutsk"],
                           ["AZOST","Atlantic/Azores"],
                           ["MHT","Pacific/Kwajalein","Pacific/Majuro"]],
                          [["CLST","America/Santiago","Antarctica/Palmer"],
                           ["WST","Antarctica/Casey","Asia/Oral",
                            "Australia/Perth","Pacific/Apia"],
                           ["MMT","Asia/Rangoon"],
                           ["ULAT","Asia/Ulaanbaatar"],
                           ["YAPT","Pacific/Yap"]],
                          [["AKST","America/Anchorage","America/Juneau",
                            "America/Nome","America/Yakutat"],
                           ["BRST","America/Araguaina","America/Fortaleza",
                            "America/Maceio","America/Recife",
                            "America/Sao Paulo"],
                           ["CLT","America/Santiago","Antarctica/Palmer"],
                           ["EGST","America/Scoresbysund"],
                           ["LKT","Asia/Colombo"],
                           ["OMST","Asia/Omsk"],
                           ["WEST","Atlantic/Canary","Atlantic/Faeroe",
                            "Atlantic/Madeira","Europe/Lisbon"],
                           ["PGT","Pacific/Port Moresby"]],
                          [["GMT","Africa/Abidjan","Africa/Accra",
                            "Africa/Bamako","Africa/Banjul","Africa/Bissau",
                            "Africa/Conakry","Africa/Dakar","Africa/Freetown",
                            "Africa/Lome","Africa/Monrovia",
                            "Africa/Nouakchott","Africa/Ouagadougou",
                            "Africa/Sao Tome","Africa/Timbuktu",
                            "America/Danmarkshavn","Atlantic/Reykjavik",
                            "Atlantic/St Helena","Europe/Belfast",
                            "Europe/Dublin","Europe/London"],
                           ["ACT","America/Eirunepe","America/Rio Branco"],
                           ["NZDT","Antarctica/McMurdo",
                            "Antarctica/South Pole","Pacific/Auckland"],
                           ["GALT","Pacific/Galapagos"]],
                          [["EDT","America/Detroit","America/Grand Turk",
                            "America/Iqaluit","America/Kentucky/Louisville",
                            "America/Kentucky/Monticello",
                            "America/Louisville","America/Montreal",
                            "America/Nassau","America/New York",
                            "America/Nipigon","America/Pangnirtung",
                            "America/Thunder Bay"],
                           ["BOT","America/La Paz"],
                           ["TMT","Asia/Ashgabat"],
                           ["PETT","Asia/Kamchatka"],
                           ["CVT","Atlantic/Cape Verde"],
                           ["FKT","Atlantic/Stanley"],
                           ["EAST","Pacific/Easter"],
                           ["NCT","Pacific/Noumea"]],
                          [["AMT","America/Boa Vista","America/Cuiaba",
                            "America/Manaus","America/Porto Velho",
                            "Asia/Yerevan"],
                           ["WGT","America/Godthab"],
                           ["UYT","America/Montevideo"],
                           ["IRKT","Asia/Irkutsk"],
                           ["EIT","Asia/Jayapura"],
                           ["KST","Asia/Pyongyang","Asia/Qyzylorda",
                            "Asia/Seoul"],
                           ["BTT","Asia/Thimphu"]],
                          [["ART","America/Buenos Aires","America/Catamarca",
                            "America/Cordoba","America/Jujuy",
                            "America/Mendoza","America/Rosario"],
                           ["VET","America/Caracas"],
                           ["NZST","Antarctica/McMurdo",
                            "Antarctica/South Pole","Pacific/Auckland"],
                           ["TRUT","Pacific/Truk"],
                           ["WAKT","Pacific/Wake"]],
                          [["CET","Africa/Algiers","Africa/Ceuta",
                            "Africa/Tunis","Arctic/Longyearbyen",
                            "Atlantic/Jan Mayen","Europe/Amsterdam",
                            "Europe/Andorra","Europe/Belgrade",
                            "Europe/Berlin","Europe/Bratislava",
                            "Europe/Brussels","Europe/Budapest",
                            "Europe/Copenhagen","Europe/Gibraltar",
                            "Europe/Ljubljana","Europe/Luxembourg",
                            "Europe/Madrid","Europe/Malta","Europe/Monaco",
                            "Europe/Oslo","Europe/Paris","Europe/Prague",
                            "Europe/Rome","Europe/San Marino",
                            "Europe/Sarajevo","Europe/Skopje",
                            "Europe/Stockholm","Europe/Tirane","Europe/Vaduz",
                            "Europe/Vatican","Europe/Vienna","Europe/Warsaw",
                            "Europe/Zagreb","Europe/Zurich"],
                           ["EST","America/Cayman","America/Detroit",
                            "America/Grand Turk",
                            "America/Indiana/Indianapolis",
                            "America/Indiana/Knox","America/Indiana/Marengo",
                            "America/Indiana/Vevay","America/Indianapolis",
                            "America/Iqaluit","America/Jamaica",
                            "America/Kentucky/Louisville",
                            "America/Kentucky/Monticello",
                            "America/Louisville","America/Montreal",
                            "America/Nassau","America/New York",
                            "America/Nipigon","America/Panama",
                            "America/Pangnirtung","America/Port-au-Prince",
                            "America/Thunder Bay","Australia/Brisbane",
                            "Australia/Hobart","Australia/Hobart",
                            "Australia/Lindeman","Australia/Melbourne",
                            "Australia/Melbourne","Australia/Sydney",
                            "Australia/Sydney"],
                           ["ANAT","Asia/Anadyr"],
                           ["IOT","Indian/Chagos"],
                           ["NRT","Pacific/Nauru"]],
                          [["GFT","America/Cayenne"],
                           ["PET","America/Lima"],
                           ["HOVT","Asia/Hovd"],
                           ["PONT","Pacific/Ponape"],
                           ["TAHT","Pacific/Tahiti"]],
                          [["COT","America/Bogota"],
                           ["KGT","Asia/Bishkek"],
                           ["TFT","Indian/Kerguelen"],
                           ["MUT","Indian/Mauritius"]],
                          [["AFT","Asia/Kabul"],["TKT","Pacific/Fakaofo"]],
                          [["WET","Africa/Casablanca","Africa/El Aaiun",
                            "Atlantic/Canary","Atlantic/Faeroe",
                            "Atlantic/Madeira","Europe/Lisbon"],
                           ["BRT","America/Araguaina","America/Belem",
                            "America/Fortaleza","America/Maceio",
                            "America/Recife","America/Sao Paulo"],
                           ["FNT","America/Noronha"],
                           ["EGT","America/Scoresbysund"],
                           ["ICT","Asia/Bangkok","Asia/Phnom Penh",
                            "Asia/Saigon","Asia/Vientiane"],
                           ["TPT","Asia/Dili"],
                           ["NFT","Pacific/Norfolk"],
                           ["GILT","Pacific/Tarawa"]]},
                         {[["PYT","America/Asuncion"],
                           ["MDT","America/Boise","America/Cambridge Bay",
                            "America/Chihuahua","America/Denver",
                            "America/Edmonton","America/Inuvik",
                            "America/Mazatlan","America/Shiprock",
                            "America/Yellowknife"],
                           ["AMST","America/Cuiaba","Asia/Yerevan"],
                           ["SAMT","Europe/Samara"]],
                          [],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                         {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}).