---
name: kazoo-application-blackhole
base_branch: origin/master
metapackage:
  - name: meta-kazoo-applications
    type: required
    branch: master
    package: kazoo-application-blackhole
base_core: kazoo
template: kazoo-application.spec.tmpl
package:
  centos7:
    name: kazoo-application-blackhole
    summary: Kazoo core application
    description: |
      Provides a websocket connection point to stream events out of KAZOO to
      your application
    app_name: blackhole
    license: MPL 2.0
    group: Productivity/Telephony
    url: https://2600hz.org/
    vendor: 2600Hz
