{application,rscmgr,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,amqp]},
              {mod,{rscmgr_app,[]}},
              {env,[]},
              {modules,[rscmgr,rscmgr_app,rscmgr_deps,rscmgr_logger,
                        rscmgr_req,rscmgr_res,rscmgr_sup]}]}.
