{application,rscmgr,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{rscmgr_app,[]}},
              {env,[]},
              {modules,[amqp_manager,rscmgr,rscmgr_app,rscmgr_deps,
                        rscmgr_logger,rscmgr_res,rscmgr_sup]}]}.
