ROOT = ../..
PROJECT = kazoo_data_cache

#EBINS = $(wildcard $(ROOT)/deps/couchbeam-*/ebin)

##SOURCES = src/wh_gen_changes.erl src/*.erl
##SOURCES = src/*.erl

all: compile

-include $(ROOT)/make/kz.mk
