{application,whistle_amqp,
             [{description,"AMQP client helpers for interacting with a AMQP server"},
              {vsn,"0.5.2"},
              {modules,[amqp_host,amqp_host_sup,amqp_manager,amqp_util,
                        whistle_amqp,whistle_amqp_app,whistle_amqp_deps,
                        whistle_amqp_sup]},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{whistle_amqp_app,[]}},
              {env,[]}]}.
