#!/bin/sh
# Copyright 2010, Scatterbit, Inc. & Jayson Vantuyl <jvantuyl@scatterbit.com>
#
# This file is part of erlctl.
#
# Erlctl is open source.  See LICENSE.txt for details.

# Adapting rabbitmqctl pieces into here

#!/bin/sh

cd `dirname $0`
export ERL_LIBS=$PWD/../lib/

EBIN=$PWD/ebin
COOKIE_FILE=$PWD/../confs/fs_conf/autoload_configs/.erlang.cookie

exec erl \
    -pa $EBIN \
    -name whappsctl@`hostname` \
    -setcookie `cat $COOKIE_FILE` \
    +Bd \
    -noshell \
    -mode interactive \
    -s erlctl_cmd \
    -extra "$0" "$@"
