{application,callflow,
             [{description,"Callflow - traversing throught the tree..."},
              {vsn,"0.0.1"},
              {modules,[callflow,callflow_app,callflow_sup,cf_call_sup,
                        cf_devices,cf_dialplan,cf_exe,cf_responder,cf_test,
                        cf_voicemail]},
              {registered,[]},
              {applications,[kernel,stdlib,crypto]},
              {mod,{callflow_app,[]}},
              {env,[]}]}.
