'components':
  'parameters':
    '$ref': 'oas3-parameters.yml'
  'schemas':
    '$ref': 'oas3-schemas.yml'
'info':
  'description': 'Crossbar - Kazoo HTTP API'
  'license':
    'name': 'Mozilla Public License 1.1'
  'title': 'Kazoo HTTP API'
  'version': '2.0.0'
'openapi': '3.0.0'
'paths':
  '$ref': 'oas3-paths.yml#/paths'
'servers':
  - 'description': 'API target server'
    'url': '{schema}://{domain}:{port}/v2'
    'variables':
      'domain':
        'default': 'localhost'
        'description': 'API sever domain name'
      'port':
        'default': '8000'
      'schema':
        'default': 'http'
        'enum':
          - 'http'
          - 'https'
