language: erlang
otp_release:
    - 17.1
    - R16B03
    - R15B03

script:
    - make
    - make dialyzer
    - make test

after_script:
    - if [ -s dialyzer/error.log ]; then cat dialyzer/error.log; fi
