{application,whistle_apps,
             [{description,"Applications on top of Whistle"},
              {vsn,"0.5.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{whistle_apps_app,[]}},
              {env,[]},
              {modules,[whapps_controller,whapps_util,whistle_apps,
                        whistle_apps_app,whistle_apps_cli,whistle_apps_deps,
                        whistle_apps_sup]}]}.
