ROOT = ../..
PROJECT = whistle_couch

EBINS = $(ROOT)/core/whistle_number_manager/ebin \
	$(wildcard $(ROOT)/deps/couchbeam-*/ebin)

SOURCES = src/wh_gen_changes.erl src/*.erl

all: compile

-include $(ROOT)/make/kz.mk
