{application,gproc,
             [{description,"GPROC"},
              {vsn,"v1.51.0-2646-gb95fb1c"},
              {id,"GPROC"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{gproc_app,[]}},
              {modules,[gproc,gproc_app,gproc_dist,gproc_info,gproc_init,
                        gproc_lib,gproc_monitor,gproc_ps,gproc_sup]}]}.
