# Paste as a Web Sequence Diagram at http://www.websequencediagrams.com

# Receive AMQP authn_req
AMQP -> webhooks_acct: authn_req for account
webhooks_acct -> hook_authn: authn_req + webhook docs

# foreach webhook
hook_authn -> callback_uri: authn_req
callback_uri -> hook_authn: authn_resp [+followup_uri]
hook_authn -> AMQP: authn_resp

# if followup_uri
hook_authn -> followup_authn: start_link
AMQP -> followup_authn: reg_success
followup_authn -> followup_uri: reg_success
#followup_authn goes down after send or after 5 seconds
