# Paste as a Web Sequence Diagram at http://www.websequencediagrams.com

# Receive AMQP authz_req
AMQP -> webhooks_acct: authz_req for account
webhooks_acct -> hook_authz: authz_req + webhook docs

# foreach webhook
hook_authz -> callback_uri: authz_req
callback_uri -> hook_authz: authz_resp [+followup_uri]
hook_authz -> AMQP: authz_resp

# if followup_uri
hook_authz -> followup_authz: start_link
AMQP -> followup_authz: authz_win
followup_authz -> followup_uri: authz_win
#followup_authz goes down after send or after 5 seconds
