# Paste as a Web Sequence Diagram at http://www.websequencediagrams.com

# Receive AMQP route_req
AMQP -> webhooks_acct: route_req for account
webhooks_acct -> hook_route: route_req + webhook docs

# foreach webhook
hook_route -> callback_uri: route_req
callback_uri --> hook_route: route_resp [+followup_uri]
hook_route -> AMQP: route_resp

# if followup_uri
hook_route -> followup_route: start_link
AMQP -> followup_route: route_win
followup_route -> followup_uri: route_win

# if call had been parked in route_resp, expect dialplan commands
followup_uri --> followup_route: dialplan (queue of commands or individual commands)
followup_route -> AMQP: dialplan
AMQP -> followup_route: call events
AMQP -> followup_route: CHANNEL_EXECUTE_COMPLETE
followup_route -> followup_uri: CHANNEL_EXECUTE_COMPLETE
followup_uri --> followup_route: more dialplan or empty
followup_route -> AMQP: more dialplan
