{application,whistle_stats,
             [{description,"Whistle Stats - An application for statistics tracking and analytics"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{whistle_stats_app,[]}},
              {env,[]},
              {modules,[wh_counter,wh_gauge,wh_timer,whistle_stats_app,
                        whistle_stats_couchbeam,whistle_stats_statsd,
                        whistle_stats_sup]}]}.
