#!/usr/bin/env ruby
require 'find'

exts = ['.erl','.hrl','.edoc','.app']
trail_ws = /[ \t]+$/
tabs = /\t/

Find.find(File.expand_path ".") do |fn|
  if File.basename(fn)[0] == ?.
    if File.directory? fn
      Find.prune # don't explore .directories
    else
      next # skip .files too
    end
  end
  if exts.include? File.extname(fn)
    f = File.open(fn)
    nl = true
    f.each_line do |line|
      nl = false
      puts "#{fn}-#{f.lineno}: trailing whitespace" if trail_ws.match line
      puts "#{fn}-#{f.lineno}: tabs" if tabs.match line
      nl = true if line[-1] == ?\n
    end
    puts "#{fn}: missing newline at end of file" if not nl
  end
end
