#!/usr/bin/env escript

display(X) when is_list(X) ->
  io:format( "~s~n", [X] );
display(X) when is_atom(X) ->
  io:format( "~s~n", [ atom_to_list(X) ] ).

info("otp_root") -> code:root_dir();
info("otp_lib") ->  code:lib_dir();
info("erts_version") -> erlang:system_info(version);
info("otp_release") -> erlang:system_info(otp_release);
info(_) -> undefined.

main( [] ) -> done;
main([ H | T ]) -> display( info(H) ), main(T).

