{application,whistle_couch,
             [{description,"Simplified interface to CouchDB"},
              {vsn,"0.5.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{whistle_couch_app,[]}},
              {env,[]},
              {modules,[change_handler,change_mgr_sup,couch_compactor,
                        couch_mgr,whistle_couch,whistle_couch_app,
                        whistle_couch_deps,whistle_couch_sup]}]}.
