#!/bin/bash

# Generate Kazoo SDKs using the Sagger file

langs=''
langs="$langs aspnet5"
langs="$langs aspnetcore"
langs="$langs async-scala"
langs="$langs bash"
langs="$langs cwiki"
langs="$langs csharp"
langs="$langs cpprest"
langs="$langs dart"
langs="$langs elixir"
langs="$langs flash"
langs="$langs python-flask"
langs="$langs go"
langs="$langs groovy"
langs="$langs java"
langs="$langs jaxrs"
langs="$langs jaxrs-cxf-client"
langs="$langs jaxrs-cxf"
langs="$langs jaxrs-resteasy"
langs="$langs jaxrs-resteasy-eap"
langs="$langs jaxrs-spec"
langs="$langs jaxrs-cxf-cdi"
langs="$langs inflector"
langs="$langs javascript"
langs="$langs javascript-closure-angular"
langs="$langs jmeter"
langs="$langs nancyfx"
langs="$langs nodejs-server"
langs="$langs objc"
langs="$langs perl"
langs="$langs php"
langs="$langs python"
langs="$langs qt5cpp"
langs="$langs ruby"
langs="$langs scala"
langs="$langs scalatra"
langs="$langs finch"
langs="$langs silex-PHP"
langs="$langs sinatra"
langs="$langs rails5"
langs="$langs slim"
langs="$langs spring"
langs="$langs java-play-framework"
langs="$langs dynamic-html"
langs="$langs html"
langs="$langs html2"
langs="$langs swagger"
langs="$langs swagger-yaml"
langs="$langs swift"
langs="$langs swift3"
langs="$langs tizen"
langs="$langs typescript-angular2"
langs="$langs typescript-angular"
langs="$langs typescript-jquery"
langs="$langs typescript-node"
langs="$langs typescript-fetch"
langs="$langs akka-scala"
langs="$langs CsharpDotNet2"
langs="$langs clojure"
langs="$langs haskell"
langs="$langs lumen"
langs="$langs go-server"
langs="$langs erlang-server"
langs="$langs undertow"
langs="$langs msf4j"
langs="$langs ze-ph"

for lang in $langs; do
    docker run --rm \
           -v ${PWD}/out:/out \
           swaggerapi/swagger-codegen-cli generate \
           -i https://raw.githubusercontent.com/2600hz/kazoo/master/applications/crossbar/priv/api/swagger.json \
           -l $lang \
           -o /out/$lang
done
