---
name: kazoo-application-hotornot
base_branch: origin/master
metapackage:
  - name: meta-kazoo-applications
    type: required
    branch: master
    package: kazoo-application-hotornot
base_core: kazoo
template: kazoo-application.spec.tmpl
package:
  centos7:
    name: kazoo-application-hotornot
    summary: Kazoo core application
    description: |
      Provides ratedeck management and rating of calls
    app_name: hotornot
    license: MPL 2.0
    group: Productivity/Telephony
    url: https://2600hz.org/
    vendor: 2600Hz
