-ifndef(FS_MOD_KAZOO_EVENT_FILTERS_HRL).

%%%
%%% this file should be removed
%%% from project when we are
%%% sure we have all the needed fs vars
%%% generated
%%%

%%%
%%% filters from mod_kazoo
%%%
-define(FS_ORIGINAL_MOD_KAZOO_EVENT_FILTERS
       ,[<<"Acquired-UUID">>
        ,<<"action">>
        ,<<"Action">>
        ,<<"alt_event_type">>
        ,<<"Answer-State">>
        ,<<"Application">>
        ,<<"Application-Data">>
        ,<<"Application-Name">>
        ,<<"Application-Response">>
        ,<<"att_xfer_replaced_by">>
        ,<<"Auth-Method">>
        ,<<"Auth-Realm">>
        ,<<"Auth-User">>
        ,<<"Bridge-A-Unique-ID">>
        ,<<"Bridge-B-Unique-ID">>
        ,<<"Call-Direction">>
        ,<<"Caller-Callee-ID-Name">>
        ,<<"Caller-Callee-ID-Number">>
        ,<<"Caller-Caller-ID-Name">>
        ,<<"Caller-Caller-ID-Number">>
        ,<<"Caller-Screen-Bit">>
        ,<<"Caller-Privacy-Hide-Name">>
        ,<<"Caller-Privacy-Hide-Number">>
        ,<<"Caller-Context">>
        ,<<"Caller-Controls">>
        ,<<"Caller-Destination-Number">>
        ,<<"Caller-Dialplan">>
        ,<<"Caller-Network-Addr">>
        ,<<"Caller-Unique-ID">>
        ,<<"Call-ID">>
        ,<<"Channel-Call-State">>
        ,<<"Channel-Call-UUID">>
        ,<<"Channel-Presence-ID">>
        ,<<"Channel-State">>
        ,<<"Chat-Permissions">>
        ,<<"Conference-Name">>
        ,<<"Conference-Profile-Name">>
        ,<<"Conference-Unique-ID">>
        ,<<"contact">>
        ,<<"Detected-Tone">>
        ,<<"dialog_state">>
        ,<<"direction">>
        ,<<"Distributed-From">>
        ,<<"DTMF-Digit">>
        ,<<"DTMF-Duration">>
        ,<<"Event-Date-Timestamp">>
        ,<<"Event-Name">>
        ,<<"Event-Subclass">>
        ,<<"expires">>
        ,<<"Expires">>
        ,<<"Ext-SIP-IP">>
        ,<<"File">>
        ,<<"FreeSWITCH-Hostname">>
        ,<<"from">>
        ,<<"Hunt-Destination-Number">>
        ,<<"ip">>
        ,<<"Message-Account">>
        ,<<"metadata">>
        ,<<"old_node_channel_uuid">>
        ,<<"Other-Leg-Callee-ID-Name">>
        ,<<"Other-Leg-Callee-ID-Number">>
        ,<<"Other-Leg-Caller-ID-Name">>
        ,<<"Other-Leg-Caller-ID-Number">>
        ,<<"Other-Leg-Destination-Number">>
        ,<<"Other-Leg-Direction">>
        ,<<"Other-Leg-Unique-ID">>
        ,<<"Other-Leg-Channel-Name">>
        ,<<"Participant-Type">>
        ,<<"Path">>
        ,<<"profile_name">>
        ,<<"Profiles">>
        ,<<"proto-specific-event-name">>
        ,<<"Raw-Application-Data">>
        ,<<"realm">>
        ,<<"Resigning-UUID">>
        ,<<"set">>
        ,<<"sip_auto_answer">>
        ,<<"sip_auth_method">>
        ,<<"sip_from_host">>
        ,<<"sip_from_user">>
        ,<<"sip_to_host">>
        ,<<"sip_to_user">>
        ,<<"sub-call-id">>
        ,<<"technology">>
        ,<<"to">>
        ,<<"Unique-ID">>
        ,<<"URL">>
        ,<<"username">>
        ,<<"variable_channel_is_moving">>
        ,<<"variable_collected_digits">>
        ,<<"variable_current_application">>
        ,<<"variable_current_application_data">>
        ,<<"variable_domain_name">>
        ,<<"variable_effective_caller_id_name">>
        ,<<"variable_effective_caller_id_number">>
        ,<<"variable_holding_uuid">>
        ,<<"variable_hold_music">>
        ,<<"variable_media_group_id">>
        ,<<"variable_originate_disposition">>
        ,<<"variable_origination_uuid">>
        ,<<"variable_playback_terminator_used">>
        ,<<"variable_presence_id">>
        ,<<"variable_record_ms">>
        ,<<"variable_recovered">>
        ,<<"variable_silence_hits_exhausted">>
        ,<<"variable_sip_auth_realm">>
        ,<<"variable_sip_from_host">>
        ,<<"variable_sip_from_user">>
        ,<<"variable_sip_from_tag">>
        ,<<"variable_sip_h_X-AUTH-IP">>
        ,<<"variable_sip_received_ip">>
        ,<<"variable_sip_to_host">>
        ,<<"variable_sip_to_user">>
        ,<<"variable_sip_to_tag">>
        ,<<"variable_sofia_profile_name">>
        ,<<"variable_transfer_history">>
        ,<<"variable_user_name">>
        ,<<"variable_endpoint_disposition">>
        ,<<"variable_originate_disposition">>
        ,<<"variable_bridge_hangup_cause">>
        ,<<"variable_hangup_cause">>
        ,<<"variable_last_bridge_proto_specific_hangup_cause">>
        ,<<"variable_proto_specific_hangup_cause">>
        ,<<"VM-Call-ID">>
        ,<<"VM-sub-call-id">>
        ,<<"whistle_application_name">>
        ,<<"whistle_application_response">>
        ,<<"whistle_event_name">>
        ,<<"kazoo_application_name">>
        ,<<"kazoo_application_response">>
        ,<<"kazoo_event_name">>
        ,<<"sip_auto_answer_notify">>
        ,<<"eavesdrop_group">>
        ,<<"origination_caller_id_name">>
        ,<<"origination_caller_id_number">>
        ,<<"origination_callee_id_name">>
        ,<<"origination_callee_id_number">>
        ,<<"sip_auth_username">>
        ,<<"sip_auth_password">>
        ,<<"effective_caller_id_name">>
        ,<<"effective_caller_id_number">>
        ,<<"effective_callee_id_name">>
        ,<<"effective_callee_id_number">>
        ,<<"variable_destination_number">>
        ,<<"variable_effective_callee_id_name">>
        ,<<"variable_effective_callee_id_number">>
        ,<<"variable_record_silence_hits">>
        ,<<"variable_refer_uuid">>
        ,<<"variable_sip_call_id">>
        ,<<"variable_sip_h_Referred-By">>
        ,<<"variable_sip_h_X-AUTH-PORT">>
        ,<<"variable_sip_loopback_req_uri">>
        ,<<"variable_sip_received_port">>
        ,<<"variable_sip_refer_to">>
        ,<<"variable_sip_req_host">>
        ,<<"variable_sip_req_uri">>
        ,<<"variable_transfer_source">>
        ,<<"variable_uuid">>

        ,<<"call-id">>
        ,<<"profile-name">>
        ,<<"from-user">>
        ,<<"from-host">>
        ,<<"presence-hosts">>
        ,<<"contact">>
        ,<<"rpid">>
        ,<<"status">>
        ,<<"expires">>
        ,<<"to-user">>
        ,<<"to-host">>
        ,<<"network-ip">>
        ,<<"network-port">>
        ,<<"username">>
        ,<<"realm">>
        ,<<"user-agent">>

        ,<<"Hangup-Cause">>
        ,<<"Unique-ID">>
        ,<<"variable_switch_r_sdp">>
        ,<<"variable_rtp_local_sdp_str">>
        ,<<"variable_sip_to_uri">>
        ,<<"variable_sip_from_uri">>
        ,<<"variable_sip_user_agent">>
        ,<<"variable_duration">>
        ,<<"variable_billsec">>
        ,<<"variable_billmsec">>
        ,<<"variable_progresssec">>
        ,<<"variable_progress_uepoch">>
        ,<<"variable_progress_media_uepoch">>
        ,<<"variable_start_uepoch">>
        ,<<"variable_digits_dialed">>
        ,<<"Member-ID">>
        ,<<"Floor">>
        ,<<"Video">>
        ,<<"Hear">>
        ,<<"Speak">>
        ,<<"Talking">>
        ,<<"Current-Energy">>
        ,<<"Energy-Level">>
        ,<<"Mute-Detect">>

        ,<<"RTMP-Session-ID">>
        ,<<"RTMP-Profile">>
        ,<<"RTMP-Flash-Version">>
        ,<<"RTMP-SWF-URL">>
        ,<<"RTMP-TC-URL">>
        ,<<"RTMP-Page-URL">>
        ,<<"User">>
        ,<<"Domain">>

        ,<<"variable_fax_bad_rows">>
        ,<<"variable_fax_document_total_pages">>
        ,<<"variable_fax_document_transferred_pages">>
        ,<<"variable_fax_ecm_used">>
        ,<<"variable_fax_result_code">>
        ,<<"variable_fax_result_text">>
        ,<<"variable_fax_success">>
        ,<<"variable_fax_transfer_rate">>
        ,<<"variable_fax_local_station_id">>
        ,<<"variable_fax_remote_station_id">>
        ,<<"variable_fax_remote_country">>
        ,<<"variable_fax_remote_vendor">>
        ,<<"variable_fax_remote_model">>
        ,<<"variable_fax_image_resolution">>
        ,<<"variable_fax_file_image_resolution">>
        ,<<"variable_fax_image_size">>
        ,<<"variable_fax_image_pixel_size">>
        ,<<"variable_fax_file_image_pixel_size">>
        ,<<"variable_fax_longest_bad_row_run">>
        ,<<"variable_fax_encoding">>
        ,<<"variable_fax_encoding_name">>
        ,<<"variable_fax_header">>
        ,<<"variable_fax_ident">>
        ,<<"variable_fax_timezone">>
        ,<<"variable_fax_doc_id">>
        ,<<"variable_fax_doc_database">>
        ,<<"variable_has_t38">>

        ,<<"variable_sdp_secure_savp_only">>
        ,<<"variable_rtp_has_crypto">>
        ,<<"variable_rtp_secure_media">>
        ,<<"variable_rtp_secure_media_confirmed">>
        ,<<"variable_rtp_secure_media_confirmed_audio">>
        ,<<"variable_rtp_secure_media_confirmed_video">>
        ,<<"variable_zrtp_secure_media">>
        ,<<"variable_zrtp_secure_media_confirmed">>
        ,<<"variable_zrtp_secure_media_confirmed_audio">>
        ,<<"variable_zrtp_secure_media_confirmed_video">>
        ,<<"sdp_secure_savp_only">>
        ,<<"rtp_has_crypto">>
        ,<<"rtp_secure_media">>
        ,<<"rtp_secure_media_confirmed">>
        ,<<"rtp_secure_media_confirmed_audio">>
        ,<<"rtp_secure_media_confirmed_video">>
        ,<<"zrtp_secure_media">>
        ,<<"zrtp_secure_media_confirmed">>
        ,<<"zrtp_secure_media_confirmed_audio">>
        ,<<"zrtp_secure_media_confirmed_video">>

        ,<<"variable_last_bridge_hangup_cause">>
        ,<<"variable_sip_redirected_by">>
        ,<<"intercepted_by">>
        ,<<"variable_bridge_uuid">>
        ,<<"Record-File-Path">>

        ,<<"variable_loopback_bowout_on_execute">>
        ,<<"variable_loopback_bowout">>
        ,<<"variable_other_loopback_leg_uuid">>
        ,<<"variable_loopback_leg">>
        ,<<"variable_is_loopback">>

        ,<<"Message-ID">>
        ,<<"Delivery-Failure">>
        ,<<"Delivery-Result-Code">>
        ]).

%%%
%%% filters from mod_kazoo
%%% -- ?FS_GENERATED_EVENT_FILTERS
%%% -- ?CONFERENCE_VARS
%%%

-define(FS_MOD_KAZOO_EVENT_FILTERS
       ,[<<"alt_event_type">>
        ,<<"Application-Name">>
        ,<<"Auth-Method">>
        ,<<"Auth-User">>
        ,<<"Caller-Screen-Bit">>
        ,<<"Caller-Privacy-Hide-Name">>
        ,<<"Caller-Privacy-Hide-Number">>
        ,<<"Caller-Controls">>
        ,<<"Caller-Network-Addr">>
        ,<<"Chat-Permissions">>
        ,<<"contact">>
        ,<<"dialog_state">>
        ,<<"direction">>
        ,<<"Distributed-From">>
        ,<<"Expires">>
        ,<<"Ext-SIP-IP">>
        ,<<"File">>
        ,<<"from">>
        ,<<"Message-Account">>
        ,<<"Other-Leg-Callee-ID-Name">>
        ,<<"Participant-Type">>
        ,<<"Path">>
        ,<<"Profiles">>
        ,<<"proto-specific-event-name">>
        ,<<"Raw-Application-Data">>
        ,<<"realm">>
        ,<<"set">>
        ,<<"sip_auto_answer">>
        ,<<"sip_from_host">>
        ,<<"sip_from_user">>
        ,<<"sub-call-id">>
        ,<<"to">>
        ,<<"URL">>
        ,<<"username">>
        ,<<"variable_holding_uuid">>
        ,<<"variable_sip_from_host">>
        ,<<"variable_sip_h_X-AUTH-IP">>
        ,<<"variable_originate_disposition">>
        ,<<"VM-Call-ID">>
        ,<<"VM-sub-call-id">>
        ,<<"whistle_application_name">>
        ,<<"whistle_application_response">>
        ,<<"whistle_event_name">>
        ,<<"sip_auto_answer_notify">>
        ,<<"eavesdrop_group">>
        ,<<"origination_caller_id_name">>
        ,<<"origination_caller_id_number">>
        ,<<"origination_callee_id_name">>
        ,<<"origination_callee_id_number">>
        ,<<"sip_auth_username">>
        ,<<"sip_auth_password">>
        ,<<"effective_caller_id_name">>
        ,<<"effective_caller_id_number">>
        ,<<"effective_callee_id_name">>
        ,<<"effective_callee_id_number">>
        ,<<"variable_destination_number">>
        ,<<"variable_sip_h_Referred-By">>
        ,<<"variable_sip_h_X-AUTH-PORT">>
        ,<<"variable_transfer_source">>
        ,<<"call-id">>
        ,<<"profile-name">>
        ,<<"from-user">>
        ,<<"from-host">>
        ,<<"presence-hosts">>
        ,<<"contact">>
        ,<<"rpid">>
        ,<<"status">>
        ,<<"expires">>
        ,<<"to-user">>
        ,<<"to-host">>
        ,<<"network-ip">>
        ,<<"network-port">>
        ,<<"username">>
        ,<<"realm">>
        ,<<"user-agent">>
        ,<<"Unique-ID">>
        ,<<"variable_progress_uepoch">>
        ,<<"variable_progress_media_uepoch">>
        ,<<"variable_start_uepoch">>
        ,<<"variable_digits_dialed">>
        ,<<"Current-Energy">>
        ,<<"RTMP-Session-ID">>
        ,<<"RTMP-Profile">>
        ,<<"RTMP-Flash-Version">>
        ,<<"RTMP-SWF-URL">>
        ,<<"RTMP-TC-URL">>
        ,<<"RTMP-Page-URL">>
        ,<<"User">>
        ,<<"Domain">>
        ,<<"variable_sdp_secure_savp_only">>
        ,<<"variable_rtp_has_crypto">>
        ,<<"variable_rtp_secure_media">>
        ,<<"variable_rtp_secure_media_confirmed">>
        ,<<"variable_rtp_secure_media_confirmed_audio">>
        ,<<"variable_rtp_secure_media_confirmed_video">>
        ,<<"variable_zrtp_secure_media">>
        ,<<"variable_zrtp_secure_media_confirmed">>
        ,<<"variable_zrtp_secure_media_confirmed_audio">>
        ,<<"variable_zrtp_secure_media_confirmed_video">>
        ,<<"sdp_secure_savp_only">>
        ,<<"rtp_has_crypto">>
        ,<<"rtp_secure_media">>
        ,<<"rtp_secure_media_confirmed">>
        ,<<"rtp_secure_media_confirmed_audio">>
        ,<<"rtp_secure_media_confirmed_video">>
        ,<<"zrtp_secure_media">>
        ,<<"zrtp_secure_media_confirmed">>
        ,<<"zrtp_secure_media_confirmed_audio">>
        ,<<"zrtp_secure_media_confirmed_video">>
        ,<<"variable_last_bridge_hangup_cause">>
        ,<<"variable_sip_redirected_by">>
        ,<<"Message-ID">>
        ,<<"Delivery-Failure">>
        ,<<"Delivery-Result-Code">>
        ]).

-define(FS_PRESERVED_EVENT_FILTERS
       ,[<<"Acquired-UUID">>
        ,<<"Action">>
        ,<<"Answer-State">>
        ,<<"Application">>
        ,<<"Application-Data">>
        ,<<"Application-Logical-Direction">>
        ,<<"Application-Response">>
        ,<<"Auth-Realm">>
        ,<<"Bridge-A-Unique-ID">>
        ,<<"Bridge-B-Unique-ID">>
        ,<<"Call-Direction">>
        ,<<"Call-ID">>
        ,<<"Call-Setup">>
        ,<<"Caller-Callee-ID-Name">>
        ,<<"Caller-Callee-ID-Number">>
        ,<<"Caller-Caller-ID-Name">>
        ,<<"Caller-Caller-ID-Number">>
        ,<<"Caller-Channel-Created-Time">>
        ,<<"Caller-Context">>
        ,<<"Caller-Destination-Number">>
        ,<<"Caller-Dialplan">>
        ,<<"Caller-Unique-ID">>
        ,<<"Channel-Call-State">>
        ,<<"Channel-Call-UUID">>
        ,<<"Channel-Name">>
        ,<<"Channel-Presence-ID">>
        ,<<"Channel-State">>
        ,<<"Conf-Name">>
        ,<<"Conference-Name">>
        ,<<"Conference-Profile-Name">>
        ,<<"Conference-Unique-ID">>
        ,<<"Controls">>
        ,<<"Core-UUID">>
        ,<<"DTMF-Digit">>
        ,<<"DTMF-Duration">>
        ,<<"Detected-Fax-Tone">>
        ,<<"Detected-Tone">>
        ,<<"Event-Date-Timestamp">>
        ,<<"Event-Name">>
        ,<<"Event-Subclass">>
        ,<<"Force-Publish-Event-State">>
        ,<<"FreeSWITCH-Hostname">>
        ,<<"Hangup-Cause">>
        ,<<"Hunt-Context">>
        ,<<"Hunt-Destination-Number">>
        ,<<"Join-Time">>
        ,<<"Other-Leg-ANI">>
        ,<<"Other-Leg-Call-ID">>
        ,<<"Other-Leg-Callee-ID-Number">>
        ,<<"Other-Leg-Caller-ID-Name">>
        ,<<"Other-Leg-Caller-ID-Number">>
        ,<<"Other-Leg-Channel-Name">>
        ,<<"Other-Leg-Destination-Number">>
        ,<<"Other-Leg-Direction">>
        ,<<"Other-Leg-RDNIS">>
        ,<<"Other-Leg-Unique-ID">>
        ,<<"Presence-Call-Direction">>
        ,<<"Publish-Channel-State">>
        ,<<"Record-File-Path">>
        ,<<"Resigning-UUID">>
        ,<<"Route-Resp-Fun">>
        ,<<"Route-Resp-Xml-Fun">>
        ,<<"Switch-Nodename">>
        ,<<"Switch-URI">>
        ,<<"Switch-URL">>
        ,<<"Unique-ID">>
        ,<<"X-AUTH-IP">>
        ,<<"X-AUTH-PORT">>
        ,<<"action">>
        ,<<"att_xfer_replaced_by">>
        ,<<"context">>
        ,<<"domain">>
        ,<<"expires">>
        ,<<"from">>
        ,<<"from_user">>
        ,<<"intercepted_by">>
        ,<<"ip">>
        ,<<"kazoo_application_name">>
        ,<<"kazoo_application_response">>
        ,<<"kazoo_event_name">>
        ,<<"metadata">>
        ,<<"old_node_channel_uuid">>
        ,<<"port">>
        ,<<"profile_name">>
        ,<<"proto">>
        ,<<"sip_auth_nonce">>
        ,<<"sip_auth_realm">>
        ,<<"sip_auth_response">>
        ,<<"sip_auth_uri">>
        ,<<"sip_call_id">>
        ,<<"sip_request_host">>
        ,<<"sip_to_host">>
        ,<<"sip_user_agent">>
        ,<<"status">>
        ,<<"technology">>
        ,<<"to_user">>
        ,<<"user">>
        ,<<"variable_billmsec">>
        ,<<"variable_billsec">>
        ,<<"variable_bridge_hangup_cause">>
        ,<<"variable_bridge_uuid">>
        ,<<"variable_channel_is_moving">>
        ,<<"variable_collected_digits">>
        ,<<"variable_current_application">>
        ,<<"variable_current_application_data">>
        ,<<"variable_domain_name">>
        ,<<"variable_duration">>
        ,<<"variable_effective_callee_id_name">>
        ,<<"variable_effective_callee_id_number">>
        ,<<"variable_effective_caller_id_name">>
        ,<<"variable_effective_caller_id_number">>
        ,<<"variable_endpoint_disposition">>
        ,<<"variable_fax_bad_rows">>
        ,<<"variable_fax_doc_database">>
        ,<<"variable_fax_doc_id">>
        ,<<"variable_fax_document_total_pages">>
        ,<<"variable_fax_document_transferred_pages">>
        ,<<"variable_fax_ecm_used">>
        ,<<"variable_fax_encoding">>
        ,<<"variable_fax_encoding_name">>
        ,<<"variable_fax_file_image_pixel_size">>
        ,<<"variable_fax_file_image_resolution">>
        ,<<"variable_fax_header">>
        ,<<"variable_fax_ident">>
        ,<<"variable_fax_image_pixel_size">>
        ,<<"variable_fax_image_resolution">>
        ,<<"variable_fax_image_size">>
        ,<<"variable_fax_local_station_id">>
        ,<<"variable_fax_longest_bad_row_run">>
        ,<<"variable_fax_remote_country">>
        ,<<"variable_fax_remote_model">>
        ,<<"variable_fax_remote_station_id">>
        ,<<"variable_fax_remote_vendor">>
        ,<<"variable_fax_result_code">>
        ,<<"variable_fax_result_text">>
        ,<<"variable_fax_success">>
        ,<<"variable_fax_timezone">>
        ,<<"variable_fax_transfer_rate">>
        ,<<"variable_hangup_cause">>
        ,<<"variable_has_t38">>
        ,<<"variable_hold_music">>
        ,<<"variable_is_loopback">>
        ,<<"variable_last_bridge_proto_specific_hangup_cause">>
        ,<<"variable_loopback_bowout">>
        ,<<"variable_loopback_bowout_on_execute">>
        ,<<"variable_loopback_leg">>
        ,<<"variable_media_group_id">>
        ,<<"variable_originate_disposition">>
        ,<<"variable_origination_callee_id_name">>
        ,<<"variable_origination_callee_id_number">>
        ,<<"variable_origination_caller_id_name">>
        ,<<"variable_origination_caller_id_number">>
        ,<<"variable_origination_uuid">>
        ,<<"variable_other_loopback_leg_uuid">>
        ,<<"variable_playback_terminator_used">>
        ,<<"variable_presence_id">>
        ,<<"variable_progresssec">>
        ,<<"variable_proto_specific_hangup_cause">>
        ,<<"variable_record_ms">>
        ,<<"variable_record_silence_hits">>
        ,<<"variable_recovered">>
        ,<<"variable_refer_uuid">>
        ,<<"variable_rtp_local_sdp_str">>
        ,<<"variable_silence_hits_exhausted">>
        ,<<"variable_sip_auth_realm">>
        ,<<"variable_sip_call_id">>
        ,<<"variable_sip_from_tag">>
        ,<<"variable_sip_from_uri">>
        ,<<"variable_sip_from_user">>
        ,<<"variable_sip_invite_domain">>
        ,<<"variable_sip_loopback_req_uri">>
        ,<<"variable_sip_origination_call_id">>
        ,<<"variable_sip_received_ip">>
        ,<<"variable_sip_received_port">>
        ,<<"variable_sip_refer_to">>
        ,<<"variable_sip_req_host">>
        ,<<"variable_sip_req_uri">>
        ,<<"variable_sip_to_host">>
        ,<<"variable_sip_to_tag">>
        ,<<"variable_sip_to_uri">>
        ,<<"variable_sip_to_user">>
        ,<<"variable_sip_user_agent">>
        ,<<"variable_sofia_profile_name">>
        ,<<"variable_switch_r_sdp">>
        ,<<"variable_transfer_history">>
        ,<<"variable_transfer_to">>
        ,<<"variable_user_name">>
        ,<<"variable_uuid">>
        ]).

-define(FS_MOD_KAZOO_EVENT_FILTERS_HRL, 'true').

-endif.
