language: erlang
otp_release:
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.1
  - 17.0
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R15B03
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02

sudo: false

script:
  - make -j app

after_success: make test
