ROOT = ..
ERLANG_MK_FILENAME = $(ROOT)/erlang.mk

DEPS_DIR = $(CURDIR)
ERLC_OPTS += +debug_info -DWITH_JIFFY=1

.DEFAULT_GOAL := all

clean::
	$(if $(wildcard ./*/), rm -rf ./*/)
	$(if $(wildcard .erlang.mk), rm -rf .erlang.mk)


include $(ROOT)/make/deps.mk
include $(ROOT)/erlang.mk
