---
name: kazoo-application-notify
base_branch: origin/master
metapackage:
  - name: meta-kazoo-applications
    type: required
    branch: master
    package: kazoo-application-notify
base_core: kazoo
template: kazoo-application.spec.tmpl
package:
  centos7:
    name: kazoo-application-notify
    summary: Kazoo core application
    description: |
      DEPRECATED! Provides notification services (emails when notifications are
      triggered) and branding capabilities
    app_name: notify
    license: MPL 2.0
    group: Productivity/Telephony
    url: https://github.com/kazoo-community/kazoo-notify
    vendor: Kazoo-Community
