{application,myapp,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{myapp_app,[]}},
              {env,[]},
              {modules,[logger,myapp_app,myapp_sup,responder_couch,
                        whistle_api]}]}.
