#!/bin/sh
# Copyright 2010, Scatterbit, Inc. & Jayson Vantuyl <jvantuyl@scatterbit.com>
#
# This file is part of erlctl.
#
# Erlctl is open source.  See LICENSE.txt for details.

# Adapting rabbitmqctl pieces into here

#!/bin/sh

cd `dirname $0`
export ERL_LIBS=$PWD/../lib/

EBIN=$PWD/ebin
ERL_COOKIE=`grep "setcookie" conf/vm.args`

exec erl \
    -pa $EBIN \
    -name whappsctl@`hostname` \
    $ERL_COOKIE \
    +Bd \
    -noshell \
    -mode interactive \
    -s erlctl_cmd \
    -extra "$0" "$@"
