ROOT = ../..
PROJECT = whistle_apps

EBINS = $(ROOT)/core/whistle_apps/ebin \
	$(ROOT)/core/kazoo_caches/ebin

TEST_EBINS = $(ROOT)/core/whistle_number_manager/ebin \
	$(ROOT)/core/whistle_config/ebin \
	$(ROOT)/core/whistle_media/ebin \
	$(ROOT)/core/whistle_couch/ebin

all: compile

-include $(ROOT)/make/kz.mk
